MariaDB/buildbot

.github/workflows/bb_containers.yml
@vladbogo this would trigger a new push on quay from the new repo (testing repo secrets mainly), merge when ready.
=> Import new repo

master-libvirt/get_number_of_ssh_conns.py, master-libvirt/watchdog_libvirt.sh, os_info.yaml
Add all OSs for which we have VMs created
=> Add remaining install/upgrade builds

master-libvirt/get_ssh_cnx_num.py, master-libvirt/watchdog_libvirt.sh
@vlad just so you can double check the python part.
=> Adapt watchdog script

.github/workflows/bb_containers.yml, ci_build_images/aocc.Dockerfile
This PR also simplify the tag and dockerfile management.
=> Add AMD compiler builder

master-libvirt/master.cfg, os_info.yaml
Here is the list:
```console
faust@db-p9-bbw1 ~ main
❯ sudo virsh list --all
Id   Name                            State
------------------------------------------------
-    bb-db-p9-bbw1-centos-7          shut off
-    bb-db-p9-bbw1-centos-8-stream   shut off
-    bb-db-p9-bbw1-centos-9-stream   shut off
-    bb-db-p9-bbw1-debian-10         shut off
-    bb-db-p9-bbw1-debian-11         shut off
-    bb-db-p9-bbw1-debian-sid        shut off
-    bb-db-p9-bbw1-rhel-8            shut off
-    bb-db-p9-bbw1-rhel-9            shut off
-    bb-db-p9-bbw1-ubuntu-1804       shut off
-    bb-db-p9-bbw1-ubuntu-2004       shut off
-    bb-db-p9-bbw1-ubuntu-2204       shut off
```
=> Add ppc64le worker

scripts/bash_lib.sh, scripts/deb-galera.sh, scripts/rpm-install.sh
See: https://buildbot.mariadb.org/#/builders/463/builds/42
Also, development_branch variable may be undefined.
=> Upgrade may take longer than 30 sec

.github/workflows/bb_containers.yml, constants.py, master-galera/master.cfg, utils.py
Generate everything so that new additions only involve adding
new entries to os_info.yaml.
=> Re-factor master-galera

ci_build_images/debian.Dockerfile
see `man 5 sources.list` (DEB822-STYLE FORMAT)
=> Debian apt introduced a new format

utils.py
=> Revert "RHEL9 does not need to be 5.5/10.1 compat"

constants.py
Remove unused variables and re-structure the file content.
=> Re-structure constants.py

.github/workflows/bb_containers.yml, ci_build_images/common.Dockerfile, ci_build_images/qpress/aio.cpp, ci_build_images/qpress/aio.hpp, ci_build_images/qpress/dirent_win.c, ci_build_images/qpress/dirent_win.h, ci_build_images/qpress/levels.c, ci_build_images/qpress/makefile, ci_build_images/qpress/qpress.cpp, ci_build_images/qpress/quicklz.c, ci_build_images/qpress/quicklz.h, ci_build_images/qpress/utilities.cpp, ci_build_images/qpress/utilities.hpp
The CI is broken for Debian sid, because of a change on apt repo configuration on sid. This will be handled properly in another PR.
=> MDEV-29043 -- add qpress to enable mariabackup.compress_qpress test

ci_build_images/debian.Dockerfile
I am wondering if dpatch is actually necessary.
=> dpatch absent from Debian sid

.github/workflows/bbm_check_conf.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, .shellcheckrc, Makefile, validate_master_cfg.sh
~~We could add the exact same logic for validating master.cfg files locally~~
done.
=> Helper for pre-commit local run

utils.py
Hi @vladbogo !
I noticed this change and I realized that the code can be simplified a little bit. Let me know what you think.
=> cleanup: Directly set default args, no need to test if none and then replace

scripts/rpm-install.sh, scripts/rpm-upgrade.sh
This would permit to verify that the new key is working in BB, see https://jira.mariadb.org/browse/MDEV-29765
=> MDEV-29765: test new key

scripts/docker-library-manifest.sh
To aid consumption in CI systems, add the following tags depending on the release status:
* verylatest - is the largest branch
* latest, being the default tag pulled, is the latest stable
* earliest, is the earliest developed MariaDB version
This will allow developers of compatible products to setup CI of quay.io/mariadb-foundation/mariadb-devel:${version} to test the earliest and the latest version of mariadb without having to maintain the tags in their CI.
=> mariadb container: verylatest/latest/earliest

ci_build_images/fedora.Dockerfile
I am creating a PR just in case it's not a good moment to push new images to quay.
@vladbogo this should solve fc37 builds.
=> Which is needed

common_factories.py, master-nonlatent/master.cfg, utils.py
Also, make sure the non-zero exit code is returned only after all the wget attempts.
=> Re-factor downloadSourceTarball

ci_build_images/centos.Dockerfile, ci_build_images/rhel.Dockerfile
no s390x looking at upstream - https://github.com/pmem/pmdk/search?q=s390x
=> libpmem for non-{rhel,centos7} rpm distros

ci_build_images/debian.Dockerfile
where we want to install buildbot user.
=> ubuntu:23.04 - build fauls because ubuntu user exists on 1000 user

constants.py, master-config.yaml-sample, master-protected-branches/master.cfg, os_info.yaml
https://docs.fedoraproject.org/en-US/releases/eol/
Status on fc36
=> fc35 - eol

.github/workflows/bb_containers.yml, ci_build_images/debian.Dockerfile
=> Install galera-4 from latest build - (fixes Debian 10/Ubuntu bionic gap)

common_factories.py
The description was too big anyway. As a repo file in CI its easier to copy/paste and use in install/upgrade tests.
=> rpm-autobake - create repo file and provide link

constants.py
For:
* aarch64
* amd64
* ppc64le
in 10.5+
=> MDEV-31035: provide centos-stream9

.github/workflows/bb_containers.yml, ci_build_images/msan.Dockerfile
Only build and not install instrumented libc++.so
=> Update MSAN dockerfile

constants.py, master-docker-nonstandard/master.cfg
Add the builder and the factory code for amd64 bintar creation
=> Add amd64-centos-7-bintar builder

docker-compose/docker-compose.yaml, docker-compose/generate-config.py, docker-compose/start.sh
Add script to auto generate the docker-compose.yaml for all the masters.
=> Auto-generate docker-compose

master-protected-branches/master.cfg
Set a spider_changed property to detect if spider changes occurred.
=> Add property for spider changes

.github/workflows/bb_containers.yml, .github/workflows/bbm_build_container.yml, Dockerfile
Use local github registry to pull hadolint tool.
=> Recover master and master web Dockerfile

common_factories.py
Give galera tests a "galera" description in mtr.
Add --big-test to actually perform the portion of galera tests covered.
=> galera: description + big-test

.github/workflows/bb_containers.yml
dummy PR just to check CI registries.
=> Test to debug Vlad's pb

master-galera/master.cfg
Force debian via env variable.
Upstream fix on autodetection https://github.com/MariaDB/galera/pull/10
=> Galera's package build has a flawed detection of Debian package build.

ci_build_images/opensuse.Dockerfile
fix failures like https://buildbot.mariadb.org/#/builders/291/builds/99
=> boost libraries for opensuse15 galera build

ci_build_images/debian.Dockerfile, master-docker-nonstandard/master.cfg
Upgrade asan to Ubuntu 22.04 and clang-14 since Ubuntu 18.04 is EOL.
=> Upgrade asan builder

common_factories.py
This will give a fix URL to fetch the latest repo file per rpm_autobake.
=> Link latest RPM repo so its at a fixed url

ci_build_images/debian.Dockerfile, master-galera/master.cfg
Thanks Nayana from IBM for testing and finding this solution.
=> Use gcc-10 on s390x to bypass compile error on Galera

master-docker-nonstandard/master.cfg
icc and icpc are now deprecated
=> Use icx and icpx

master-galera/master.cfg
This will be used to trigger builds on dev environment.
=> Wait for changes from galera fork

master-galera/master.cfg
=> galera rpm fix

.github/workflows/bbm_deploy.yml, Dockerfile, common_factories.py, constants.py, docker-compose/.env, docker-compose/.env.dev, docker-compose/docker-compose.yaml, docker-compose/generate-config.py, docker-compose/nginx/conf.d/ci.dev.mariadb.org.conf, locks.py, master-docker-nonstandard/master.cfg, master-galera/master.cfg, master-private.cfg-sample
=> Sync main with dev

master-galera/master.cfg
The correct executable name is g++-10
=> Use g++-10 instead of g++10

ci_build_images/opensuse.Dockerfile
create repo needed for https://buildbot.dev.mariadb.org/#/builders/13/builds/4
=> bb-worker:opensuse15- bump to 15.5 + createrepo_c package

constants.py, master-docker-nonstandard/master.cfg
Add amd64-debian-12-rocksdb builder
=> Add_rocksdb

ci_build_images/opensuse.Dockerfile
I was wrong in #233.
Shouldn't believe everything I read on the internet.
=> bb-worker:opensuse15 + createrepo package

master-docker-nonstandard/master.cfg, master-nonlatent/master.cfg, master-protected-branches/master.cfg, master-web/templates/grid_view/grid.jade
Add the tag to all builders used for branch protection. Also update the
template to show the filtering tags.
Needs master-web image re-creation
=> Tag_filter

docker-compose/start.sh
Otherwise it needs to be delete before started
=> Permits the container to be restarted

master-libvirt/master.cfg, scripts/bash_lib.sh
Should fix https://buildbot.dev.mariadb.org/#/builders/198/builds/1.
The manual invocation needs to be tested too.
=> Make script working with new dev environment

constants.py, master-nonlatent/master.cfg, master-private.cfg-sample
Enable the builder - more changes are probably needed, but this will allow testing
=> Enable FreeBSD builder

master.cfg, scripts/bash_lib.sh, scripts/deb-install.sh, utils.py
Sorry for the quite big PR. For ease of review, concentrate on the addition in utils.py since almost all of the master.cfg changes are Black formatting.
=> Create deb repository with reprepro tool

docker-compose/.env, docker-compose/.env.dev, docker-compose/nginx/conf.d/ci.conf
And handle future prod/env deployment
=> Make some extensions show in browser

master-docker-nonstandard/master.cfg, master-protected-branches/master.cfg
This reverts commit ebbfe21b33b5e18bd210002bef4f4e08e91545da.
=> Revert "Add -DHAVE_valgrind to Debug builders"

utils.py
https://jira.mariadb.org/browse/MDBF-637
=> Copy artifacts since reprepro does not work on all platforms

.github/workflows/bbw_build_container.yml, ci_build_images/debian.Dockerfile, os_info.yaml
Arches there: http://soaphub.org/imagehub/?q=ubuntu&n=library&p=1
=> Add Ubuntu-24.04 noble

master-docker-nonstandard/master.cfg, master-private.cfg-sample, master.cfg, schedulers_definition.py
The goal of this builder is to prepare the packages for release.
=> Add release-prep builder

scripts/rpm-install.sh
mysql.user table already exists!
Run mysql_upgrade, not mysql_install_db
=> There is no reason for this

scripts/bash_lib.sh
Try to install from archive.mariadb.org if deb.mariadb.org does not contain packages.
=> Replicate what we do on RPM

constants.py, os_info.yaml
* amd64-almalinux-{8,9}
* x86-debian-11
* amd64-rockylinux-{8,9}
=> Add builders

dockerfiles/ecofiles/test-php.sh
A make error can result, so it doesn't always
work from a dirty build dir, just build from scratch in this case.
+ '[' /code/master/configure -nt config.log ']' make -j $(nproc)
++ nproc
+ make -j 64 make: *** No rule to make target '/code/master/Zend/zend_rc_debug.h', needed by 'ext/opcache/ZendAccelerator.lo'.  Stop. program finished with exit code 2
=> php: retry on make error

ci_build_images/debian.Dockerfile
=> MDBF-659: gdb added as dependency

cross-reference/crossreference/cr/models.py
Like:
spider/feature.checksum_table_parallel_extended
=> MDBF-662: cross reference - test can contain /

constants.py, master-nonlatent/master.cfg
Mark the MTR as warning and do not mark the build as failure
=> Report aarch64-macos status to GitHub

master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg
The name is too long for the database field
=> Fix database error for fulltest run

docker-compose/docker-compose.yaml, docker-compose/generate-config.py, master-bintars/buildbot.tac, master-bintars/master.cfg, master-private.cfg-sample, validate_master_cfg.sh
This should be 90% ready to start a vm using the runvm script. The paths to the VMs need adjustemnts
=> Add new master to handle bintar KVMs

constants.py
* amd64-kvm-ubuntu-1210-bintar
* amd64-kvm-ubuntu-1604-bintar
=> Trigger the kvm bintar builders

master-bintars/master.cfg, script_templates/bintar_compile.sh, utils.py
Add a new template for scripts used in buildbot steps. To make them more readable the file is a .sh file. This makes pre-commit fail
=> Add bintar compile step

constants.py, master-bintars/master.cfg
Also, fix using the correct image for ubuntu 16.04
=> Only trigger bintar builders for the required branches

.github/workflows/bbw_build_container.yml, constants.py, os_info.yaml
Currently about beta phase with release in almost a month
https://fedorapeople.org/groups/schedule/f-40/f-40-key-tasks.html
I haven't tested the container build yet, leaving that for CI.
Fedora upstream targetting to package 10.11.
=> add fedora 40

utils.py
See: https://buildbot.dev.mariadb.org/#/builders/285/builds/17/steps/3/logs/stdio
=> Less verbose wget output

common_factories.py, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg, master.cfg, utils.py
=> Function for env print

common_factories.py
slightly a cleanup, but trying to work out why [amd64-fedora-39](https://buildbot.dev.mariadb.org/#/builders/57/builds/18) isn't running galera tests despite listed in `builders_galera_mtr`.
=> common: change f_quick_build argument to just "factory"

master-nonlatent/master.cfg
as its on a separate builder in test env, there's no conflicts.
=> wordpress: no environ property

constants.py
=> Trigger aarch alma linux builders

master-nonlatent/master.cfg
This aims to prevent overloading the machines
=> Decrease --parallel for mac

master-docker-nonstandard-2/master.cfg
=> Increase shm_size for x86-debian-12-full-test builder

common_factories.py
last-N-failed: remove duplicates from the test list
=> last-N-failed: remove duplicates from the test list

master-protected-branches/master.cfg
Add the flag to the amd64-ubuntu-2004-debug builder
=> MDBF-654 Add -DEXTRA_DEBUG

master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg
There is no reason to wait for more than 1 hour. I that happens, we need to fix the slowness of the environment/machine and not block queues.
=> Reduce timeout

schedulers_definition.py, utils.py
According to Jira Item MDBF-713, scheduler Helper Functions were moved in schedulers_definition.py
=> MDBF-713 - Move scheduler helper functions

.github/workflows/bbw_build_container.yml, ci_build_images/jepsen-mysql.Dockerfile, ci_build_images/qpress.Dockerfile
Based on https://github.com/vlad-lesin/jepsen-mysql/tree/main/mariadb-docker
=> Add jepsen-mysql tests images

master-docker-nonstandard-2/master.cfg, master-protected-branches/master.cfg, master-web/master.cfg, script_templates/jepsen_mysql.sh, utils.py
Based on
https://github.com/vlad-lesin/jepsen-mysql/tree/main/mariadb-docker
=> Jepsen tests implementation

master-protected-branches/master.cfg, schedulers_definition.py
=> add jepsen scheduler

master-docker-nonstandard-2/master.cfg
This is needed to set up properties in the script
=> Use util.Interpolate

.github/workflows/bbm_build_container.yml
The files rarely change, so having the option to trigger the action manually would help
=> Manually run bbm_build_container

master-docker-nonstandard/master.cfg
opps: https://buildbot.dev.mariadb.org/#/builders/371/builds/1/steps/6/logs/stdio
fix introduced in #483
=> asan (2404) - remove package from build args

schedulers_definition.py
This will solve pre-commit errors
=> Fix python black

common_factories.py, constants.py, master-nonlatent/master.cfg, utils.py
FreeBSD builder now supports Galera test suites.
=> MDBF-701 - FreeBSD builder to run Galera tests

validate_master_cfg.sh
Just to clean my git stash before I forget ;)
=> Better bash formatting

.github/workflows/pre-commit.yml, Makefile
=> Fix pre commit

Makefile
https://github.com/pypa/setuptools/issues/4519#issuecomment-2257563354
=> fixup! Pin setuptools and use it

.github/workflows/bbm_build_container.yml, .github/workflows/bbm_deploy.yml, .github/workflows/bbw_build_container.yml, .github/workflows/bbw_build_container_release.yml, .github/workflows/bbw_build_container_rhel.yml, .github/workflows/eco_containers.yml
This makes transition to the 'new' latest more predictable.
=> Pin GH action runner version

scripts/docker-library-manifest.sh
=> docker-library-manifest: main is very latest

master-bintars/master.cfg
port should be INT to support +=
=> Fix MDBF-709 - port

common_factories.py
install tests are failing like:  https://buildbot.mariadb.org/#/builders/610/builds/1767
=> {Alma,rocky}linux-8 module_hotfixes

master-docker-nonstandard/master.cfg, master-nonlatent/master.cfg, master.cfg
I'm not sure where the filtering comes in on the bb display.
These where some of the things needed to quickly exclude.
=> MDBF-767 Add experimental and bleeding-edge worker tags

master.cfg
- autobake builders use tags list.
=> Fix release_packages tags in MDBF-767

utils.py
=> Save .log files to allow easier debugging

script_templates/jepsen_mariadb.sh
=> jepsen fix concurrency argument

.github/workflows/bbw_build_container_rhel.yml
Manually dispatch RHEL image builds.
=> Manually dispatch RHEL builds

ci_build_images/rhel.Dockerfile
=> Add eigen3 for RHEL

.github/workflows/build-fedora-based.yml
Postfix to ef48470010ad6ac2eb0f752d1454f102c54695f9
=> MDBF-798: fedora38 eol

.github/workflows/build-opensuse.pip-based.yml, .github/workflows/build-sles.pip-based.yml, constants.py, master.cfg, os_info.yaml
Closes https://github.com/MariaDB/buildbot/pull/519
=> Fix for MDBF-779 SLES/OpenSUSE 15.5 bb config #519 

scripts/deb-upgrade.sh
Use ( deb | archive ).mariadb.org to download the Packages file. This file is mandatory for both the 'All' and 'Columnstore' test types, exit with error if it is not found.
Apply uniq to remove duplicate values in the package list and sort the list for readability."
**Tests:**
`./deb-upgrade.sh https://buildbot.dev.mariadb.org/#/builders/234/builds/9`
yields
`INFO: Package_list: libmariadb3 libmariadb3-compat libmariadbclient18 libmariadbd19 libmariadbd-dev libmariadb-dev libmariadb-dev-compat libmysqlclient18 mariadb-backup mariadb-client mariadb-client-core mariadb-common mariadb-plugin-connect mariadb-plugin-cracklib-password-check mariadb-plugin-gssapi-client mariadb-plugin-gssapi-server mariadb-plugin-hashicorp-key-management mariadb-plugin-mroonga mariadb-plugin-oqgraph …
=> MDBF-802 - deb-upgrade.sh does not fetch Packages file from releases

scripts/deb-upgrade.sh
Align code with old-bb and peform an extra restart after the previous version is installed so plugins are loaded.
=> [MDBF-800][Post-Fix] - Extra restart needed due to MDEV-23061

constants.py, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg
Expanding test suite on LastNFailedBuilds and full test to include cursor protocol.
Also add view the the LastNFailedBuilds.
=> Mdev 31050 cursor protocol

scripts/rpm-upgrade.sh
Filter out galera | columnstore. Match old BB configuration.
=> [MDBF-800][Post-fix] - Filter RPM package_list in test_mode='ALL'

.github/workflows/build-workflow-dispatcher.yml
Fix workflow dispatcher errors:
https://github.com/MariaDB/buildbot/actions/runs/11322242668
=> CentOS based workflow is no longer present.

docker-compose/start-bbm-web.sh, docker-compose/start.sh
Fix pre-commit: SC2086 - Double quote to prevent globbing
=> SC2086 - Double quote to prevent globbing

README.md
Adapt workflow badges to new bbw container workflows
=> Fix workflow badges

.github/workflows/bbm_build_container.yml
Allow pushing master images from DEV
=> Allow pushing master images from DEV

master-libvirt/master.cfg
Fix Deb Upgrade step (missing upgrade)
=> Fix Deb Upgrade step (missing upgrade)

common_factories.py, constants.py
=> MDEV-31005 cursor protocol last n builders

master-docker-nonstandard/master.cfg, master-galera/master.cfg, master-private.cfg-sample
- all ppc64le galera builders moved to osuosl
- ub2004 debug and without-server moved to osuosl
Update ppc64le entries in master-private sample.
=> Resource optimization for ppc64le

minio/README.md, minio/docker-compose.yaml, minio/nginx/conf.d/minio.conf, minio/nginx/nginx.conf, rsync.exclude
Further improvements: GitHub Actions workflow to deploy the services on the minio.mariadb.org host.
=> MinIO deployment configuration

master-web/templates/grid_view/grid.jade, master-web/templates/home.jade
removes no longer maintained versions
https://mariadb.org/about/#maintenance-policy
=> grid: branches of maintained versions update

common_factories.py
MTR env for bucket is S3_BUCKET
=> MDBF-821 - MTR env for bucket is S3_BUCKET

.github/dependabot.yml
Not sure about it so far but let's see if that's helpful and not too noisy.
=> Implement dependabot for the repository

docker-compose/crossbar/dev/config.json, docker-compose/crossbar/prod/config.json, docker-compose/docker-compose.yaml, docker-compose/generate-config.py
Took the configuration from `hz-dev-bbm` container
and added **Production** fine-tunings (options) for WS protocol.
```
"options": {
"auto_ping_interval": 60000,
"auto_ping_timeout": 80000
}
```
=> MDBF-861 - CrossBar Ping Interval/Timeout

utils.py
=> Fixup #2. Missing key value and wrong TypeHint for return type

.github/workflows/build-opensuse.pip-based.yml, .github/workflows/build-sles.pip-based.yml, constants.py, master.cfg, os_info.yaml
=> MDBF-897 SLES/openSUSE 15.5 EOL

constants.py
Let buildbot generate install and upgrade builders for SLES in master-libvirt
=> MDBF-899 - Enable SLES install / upgrade tests

scripts/docker-library-build.sh
minor error correction while I noticed.
=> docker-library build - incorrect parent is an error

master-nonlatent/master.cfg
- **Remove unused imports - bad rebase conflict resolution**
- **Fixup master-refactor windows save packages**
=> MDBF-961: Post master-refactor fixup

constants.py, master-web/templates/grid_view/grid.jade, master-web/templates/home.jade, scripts/bash_lib.sh
Next version after 11.8 is 12.0
=> MDBF-962 - Buildbot Build for 12.0

master-private.cfg-sample, validate_master_cfg.sh
Validate master-libvirt using a dummy connection
=> Validate master-libvirt using a dummy connection

.github/workflows/build-fedora-based.yml, constants.py, os_info.yaml
=> MDBF-1026 - Fedora 39 is end of life

constants.py
Thanks to @fauust , we now have a working Stream10 VM on ppc64le
=> MDBF-847 - centos-stream-10 ppc64le VM is now available

master-docker-nonstandard-2/master.cfg
Fix MTR invocation for clang-20 MSAN builder
=> MDBF-793 - fix MTR invocation

constants.py, master-web/templates/grid_view/grid.jade, master-web/templates/home.jade
=> MDBF-1054 - Add 12.1, 12.2, 12.3

docker-compose/nginx/templates/bb.conf.template, docker-compose/nginx/templates/ci.conf.template
=> AI bots are too agressive, disallow them

.github/workflows/pre-commit.yml, .github/workflows/unittests.yml, Makefile
- use the same py major version of production master
- uv will automatically install python 3.9 if is missing from your system
- use --seed to install pip / setuptools / wheel into the venv
=> Use uv for creating the buildbot environment

ci_build_images/centos.Dockerfile
=> MDBF-1038: Lzo missing

.github/workflows/build-debian-based.yml, constants.py, master-private.cfg-sample, os_info.yaml
Hard freeze reached
https://lists.debian.org/debian-devel-announce/2025/05/msg00004.html
=> MDBF-848 - Add Debian 13 (Trixie)

scripts/rpm-install.sh
otherwise can cause buildbot timeouts
=> Disable Columnstore tests until MCOL-5825 is sorted out

constants.py, master-protected-branches/master.cfg
=> MDBF-1060 - F40 is EOL, next branch protection builder is F41

master-migration/master.cfg, master-private.cfg-sample
Host specs:
- RHEL9
- AMD EPYC 9454P 48-Core
- 256 gb ram
- buildbot-worker service (dev|prod)
=> Add hz-bbw9 to master-migration
