ci_build_images/rhel7.Dockerfile
https://buildbot.mariadb.org/#/builders/438/builds/2
=> Rhel7 needs systemd-devel to produce rpm for systemd devices

scripts/docker-library-build-and-test.sh
https://github.com/MariaDB/server/commit/c168e16782fc449f61412e5afc1c01d59b77c675 up to 10.10 now as evident on GH
=> docker-library: MDEV-28628 fully merged

.github/workflows/bbm_build_container.yml, .github/workflows/bbm_check_conf.yml, Dockerfile
Rollback the multi-stage container build:
Copying the python virtual environment from the builder container to the final container is not a good approach since it's not guaranteed to work. That's why we prefer to install everything needed in the final container.
=> Build both master and master-web images

ci_build_images/debian.Dockerfile
Closes: #MariaDB/mariadb.org-tools/pull/130
=> MDEV-28153: use static control dependencies adjusted by autobake-deb.sh

.github/workflows/bbm_check_conf.yml, master-docker-nonstandard/buildbot.tac, master-docker-nonstandard/dockerfiles, master-docker-nonstandard/master.cfg, master-galera/master.cfg, master.cfg, schedulers_definition.py, utils.py
The non standard builders (e.g. MSAN, valgrind, eco, etc) need to be manually
defined. Move them to a separate master so that the rest of the builders
can be defined automatically based on the os_info.yaml file content.
=> Move non standard builders to a separate master

utils.py
5.5/ 10.1 shouldn't be a compat issue thanks Elena. And there's no package so lets not make the autobake install fail.
=> RHEL9 does not need to be 5.5/10.1 compat

scripts/bash_lib.sh
Make sure that we provide BB_CI env var for **all** libvirt tests before
merging this.
=> Improve CI context detection

scripts/rpm-install.sh
Error is:
Errors during downloading metadata for repository 'galera':
- Status code: 404 for
https://mirror.mariadb.org/yum/10.8/centosstream8-amd64/repodata/repomd.xml
(IP: 162.55.42.214)
Error: Failed to download metadata for repo 'galera': Cannot download
repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
=> Do not setup galera repo if absent from mirror

ci_build_images/centos.Dockerfile
See:
https://buildbot.mariadb.org/#/builders/359/builds/954
```console
-- Looking for malloc_stats_print in c - not found
CMake Error at cmake/jemalloc.cmake:38 (MESSAGE):
jemalloc is not found
Call Stack (most recent call first):
storage/tokudb/CMakeLists.txt:53 (CHECK_JEMALLOC)
```
For some reason this error only appears on AMD64
=> Jemalloc-devel is missing from centosstream8 image

utils.py
@grooverdan not sure if it's the best approach, but I have no other idea
=> RHEL 9/CentOS 9 does not need to be 5.5/10.1 compat

constants.py, master-libvirt/get_ssh_cnx_num.py, os_info.yaml
Add a new flag to os_info.yaml that indicates that the addition on
install/upgrade builds should be skipped or not. This needs to be used
for unreleased operating systems.
=> Do not add install/upgrade builds for unreleased OS

ci_build_images/rhel7.Dockerfile
This is needed to install cracklib-devel, lz4-devel, pcre2-devel
and snappy-devel.
=> Enable optional repo for RHEL 7

.github/workflows/bb_containers.yml
Error was on rhel7:
| qpress: Error opening source file '/etc/system-fips' - aborted
or on centos7:
| qpress: Error opening source file '/etc/alternatives/jstat.1.gz' - aborted
=> qpress: some files from /etc may not be readable

.github/workflows/eco_containers.yml, eco_build_images/wordpress_phpunit_test_runner.Dockerfile, eco_build_images/wordpress_phpunit_test_runner.entrypoint, eco_build_images/wordpress_phpunit_test_runner.env, master-nonlatent/master.cfg, schedulers_definition.py, scripts/docker-library-build.sh, scripts/docker-library-manifest.sh, scripts/docker-library-test.sh
Restructure docker_library builder to separate steps with the WordPress builder triggered in the middle.
=> MDBF-467: Add WordPress builder

utils.py
The public IP should be used for a very limited list of workers (those where wireguard is not available).
Here is a script to list all public IP connected to the master:
```bash
#!/usr/bin/env bash
ssh hz-bbm1 "sudo netstat -plantu | grep -E \"135.181.143.118:99..|135.181.143.118:10000\"" |
awk '{print $5}' |
cut -d ":" -f1 |
sort -u
```
=> Default to wireguard interface

scripts/rpm-install.sh
See:
https://access.redhat.com/discussions/3030711?tour=8
Error was:
```
Red Hat Enterprise Linux 8 for ARM 64 - BaseOS  201  B/s | 357  B     00:01
Errors during downloading metadata for repository 'rhel-8-for-aarch64-baseos-rpms':
- Status code: 403 for https://cdn.redhat.com/content/dist/rhel8/8/aarch64/baseos/os/repodata/repomd.xml (IP: 2.18.220.251)
Error: Failed to download metadata for repo 'rhel-8-for-aarch64-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
=> Need to refresh subscription to use rhel repo

master-nonlatent/master.cfg
This is needed for the savePackage step to be true and the manifest to be generated for the worker.
=> docker library: save_packages True for worker

ci_build_images/debian.Dockerfile
Error:
```console
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find GnuTLS (missing: GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR)
(Required is at least version "3.3.24")
Call Stack (most recent call first):
/usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake-3.22/Modules/FindGnuTLS.cmake:68 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
libmariadb/CMakeLists.txt:311 (FIND_PACKAGE)
```
=> Gnutls-dev is needed

master-nonlatent/master.cfg
buildah rmi was incorrect and created errors where there image is used in a manifest.
buildah rmi mariadb-28609-amd64-wordpress
in dir /home/buildbot/amd64-rhel8-wordpress/build (timeout 1200 secs)
....
1 error occurred:
* Image used by 559e7e0431b04f9dbf41cd9491a477eb35a3166b1ea98ee29733a6fff986cd09: image is in use by a container
As the mariadb-X-amd64-wordpress image is created with `podman tag` it can be removed with `podman untag`.
Tested with podman version on server:
```
[dan@bb-rhel8-docker ~]$ podman  tag quay.io/mariadb-foundation/mariadb-devel:10.6 quay.io/mariadb-foundation/mariadb-devel:10.6a
[dan@bb-rhel8-docker ~]$ podman untag quay.io/mariadb-foundation/mariadb-devel:10.6a
```
=> wordpress cleanup

ci_build_images/centos.Dockerfile, ci_build_images/rhel.Dockerfile
Double quote to prevent globbing and word splitting.
=> Address hadolint SC2086 info

common_factories.py
This was removed in #74 / 54d17d4682c2f51cc9e12c1aed99917316b29146.
=> rpm-autobake factory - no sha256sums.txt file generated

.github/workflows/bb_containers.yml, .github/workflows/bbm_build_container.yml
This remove adherence to GH CI and make image generation less obscure. The fact that images are created in a serial order by platform should also help to find which platform is not building and help debugging.
=> Use podman commands instead of GH action

ci_build_images/centos.Dockerfile, ci_build_images/centos7.Dockerfile, ci_build_images/debian.Dockerfile, ci_build_images/fedora.Dockerfile, ci_build_images/rhel.Dockerfile, ci_build_images/rhel7.Dockerfile
Export WSREP_PROVIDER for MTR use.
While this is a galera-4 provider, mtr will
ignore this if running 10.3 after doing a version check.
opensuse galera package not included as it pulled
in MariaDB-10.4 as a dependency. Others allowed a
stand alone install.
Bionic has galera-3 only. 10.3 uses galera-3. It will be out of date by the time we add it here.
=> MDBF-337: add galera package to builders

.github/workflows/bb_containers.yml, ci_build_images/msan.Dockerfile
MSAN has been built according to the https://libcxx.llvm.org/BuildingLibcxx.html instructions
There is also an issue  with debian source package https://github.com/llvm/llvm-project/issues/59240 which leads to some warnings during libcxx build.
And I've run `make install` which moved built libraries and headers to the `/usr/local`. Is it fine or they have to reside somewhere else?
=> [MDBF-443] Create BuildBot worker image with MSAN

.github/workflows/bb_containers.yml, constants.py
https://packages.debian.org/sid/mariadb-server
https://buildbot.mariadb.org/#/builders/431/builds/2814
Install failures happen otherwise:
```
The following packages have unmet dependencies:
libmariadb-dev-dbgsym : Depends: libmariadb-dev (= 1:10.6.12+maria~debsid) but 1:10.11.1-1 is to be installed
libmariadb3 : Breaks: libmariadbclient18 but 1:10.6.12+maria~debsid is to be installed
libmariadb3-dbgsym : Depends: libmariadb3 (= 1:10.6.12+maria~debsid) but 1:10.11.1-1 is to be installed
libmariadbclient18 : Depends: libmariadb3 (= 1:10.6.12+maria~debsid) but 1:10.11.1-1 is to be installed
libmariadbd19-dbgsym : Depends: libmariadbd19 (= 1:10.6.12+maria~debsid) but 1:10.11.1-1 is to be installed
libmysqlclient18 : Depends: libmariadb3 (= 1:10.6.12+maria~debsid) but 1:10.11.1-1 is to be …
```
=> Debian sid has 10.11 now, so define that as the minimum version

master-docker-nonstandard/master.cfg, master-galera/master.cfg, master-libvirt/master.cfg, master-nonlatent/master.cfg, master-protected-branches/master.cfg, master-web/master.cfg, master.cfg
There is no reason to use DNS resolution for crossbar and we also probably need to only listen locally for that service.
=> Skip DNS resolution by using localhost

ci_build_images/opensuse.Dockerfile
Also retriggered rhel9/centosstream9 on https://github.com/MariaDB/buildbot/actions/runs/4284376503 as bb was running without the rpmlinter on those.
=> MDBF-440: add rpm lint to opensuse

ci_build_images/opensuse.Dockerfile
ref: https://buildbot.mariadb.org/#/builders/197/builds/15507
=> opensuse: jemalloc still needed in 10.4 (tokudb)

Dockerfile
Error is:
```console
error isbinaryfile@5.0.0: The engine "node" is incompatible with this module. Expected version ">= 14.0.0". Got "12.22.12"
error Found incompatible module.
```
Suggested from: https://stackoverflow.com/questions/66429081/the-engine-node-is-incompatible-with-this-module-expected-version-12-x-got
=> Try to fix the master-web build

constants.py, schedulers_definition.py, utils.py
Only trigger the protected branches builders if they are defined to run for a particular branch.
=> MDBF-536: Correctly trigger builds

utils.py
compgen based on https://stackoverflow.com/questions/2937407/test-whether-a-glob-has-any-matches-in-bash#34195247
All instances of calling "createVar" are with bash.
=> createVar (tar) - include exe and datadir on coredump

common_factories.py, constants.py, utils.py
Add mtr tests on a few BB workers.
Debian/Ubuntu get Galera from MDRB bb (very latest) and RPM gets it from the distro. Both should run correctly.
Also choose BB workers that don't run 10.3 as no Galera-3 providers are installed.
=> MDBF-337: enable galera mtr tests

eco_build_images/wordpress_phpunit_test_runner.Dockerfile
wordpress_phpunit_test_runner updated based on upstream.
hoping to fix:
https://buildbot.mariadb.org/#/builders/505/builds/1280/steps/4/logs/stdio
There was 1 failure:
1) Tests_Admin_WpAutomaticUpdater::test_is_allowed_dir_should_return_false_if_open_basedir_is_set_and_path_is_not_allowed Failed asserting that true is false.
I updated my https://github.com/grooverdan/phpunit-test-runner branch so this will regenerate based on this.
=> eco: wordpress_phpunit_test_runner trigger update

eco_build_images/wordpress_phpunit_test_runner.env
Upstream flaw in testcase:
Tests_Admin_WpAutomaticUpdater::test_is_allowed_dir_should_return_false_if_open_basedir_is_set_and_path_is_not_allowed
Thanks to invaluable assitance from Colin Stewart.
=> wp: work around test failure

scripts/deb-galera.sh
There's insufficient logs to show what is going on.
A missing pid file shows its terminated, so no point looping.
https://buildbot.mariadb.org/#/builders/436/builds/7600/steps/4/logs/stdio
=> deb-autobake-install - galera failures - insufficient logs

ci_build_images/debian.Dockerfile, ci_build_images/rhel7.Dockerfile
Install default-jdk on debian and java-1.8.0-openjdk-devel on rhel7
=> MDBF-560 Add JDK to CI build images

common_factories.py, master-protected-branches/master.cfg
=> Enable spider tests if spider changes are detected

utils.py
Saving cnf files is already under the mysql-test/var/log/ directory so no additional save is required.
=> core save - parallel mtr as additional numbered path

ci_build_images/centos.Dockerfile, ci_build_images/centos7.Dockerfile, ci_build_images/debian.Dockerfile, ci_build_images/fedora.Dockerfile, ci_build_images/rhel.Dockerfile, ci_build_images/rhel7.Dockerfile
- Based on patch 658b914996807f9f33999bd3daf399101f99a32c we need `JNI` to be installed `jni.h` and respective `JAVA_AWT_LIBRARY` and `JAVA_AWT_INCLUDE_PATH` to be set,and that is done from `jdk` instead of `headless`.
- Note for rpm: `-devel` should be equals to `jdk`, maybe the change is not needed.
=> Use full dependencies for JDK

ci_build_images/debian.Dockerfile
Problem was:
```console
Err:4 https://buildbot.mariadb.net/archive/builds/mariadb-4.x/latest/kvm-deb-trixie-amd64-gal/debs ./ Packages
404  Not Found [IP: 104.18.21.47 443]
```
=> Debian sid image now has trixie codename

eco_build_images/wordpress_phpunit_test_runner.Dockerfile
Bump to php-8.2 and new npm versions
=> eco wordpress - resolve upstream #178

common_factories.py, master-docker-nonstandard/master.cfg, scripts/aix-build-and-test.sh, utils.py
* Only save *.err files
* Set MTR --max-save-datadir=10
=> Update var.tar.gz creation

ci_build_images/centos.Dockerfile, ci_build_images/centos7.Dockerfile, ci_build_images/fedora.Dockerfile, ci_build_images/rhel.Dockerfile, ci_build_images/rhel7.Dockerfile
right for fedora, lets see if other builds pick the package up.
resolves failures on https://buildbot.mariadb.org/#/grid?branch=preview-11.3-preview
ssl_autoverify
=> RPM ci images - add perl-autodie (for preview-11.3-preview branch)

constants.py
To keep non-latent master changes to a minium we plan for 4 more 11.x series releases.
This way non-latent workers will pick up jobs as these new branches becomes active (every 3 months).
=> Add to branches_main

.github/workflows/bb_containers.yml
The build of rhel9 images needs more space.
=> Somme GH runners are out of space

utils.py
like ./mysql-test/var/log/main.func_json_notembedded/core.gz
example - https://ci.mariadb.org/38839/logs/s390x-sles-12/var.tar.gz
build - https://buildbot.mariadb.org/#/builders/504/builds/7945
mtr timeout and hit the assert, so core was in different location.
=> core detection on SIGASERT by mtr

cross-reference/crossreference/cr/models.py, cross-reference/crossreference/cr/router.py, cross-reference/crossreference/cr/templates/cr/index.html
Correctly fetch the builder id
=> Fix build URL in cross reference

common_factories.py, master-protected-branches/master.cfg
MDBF-535 enables conditional spider tests for protected branches in Buildbot when the commit has touched spider code. It is time to remove this condition as the trial shows these spider test runs have generally not been a problem for development.
=> MDBF-598 Remove checks for spider changes

scripts/bash_lib.sh
The previous release detection mechanism was broken. Also since we do not handle correctly when BB should do install and upgrade tests, let's skip (by not failing) test that can't succeed since packages where not released.
=> Fix previous release detection

master-galera/master.cfg, master.cfg
Steps where executed in root, so the target is a absolute file path.
=> repo symlink in /packages/ (for galera dev)

common_factories.py, master.cfg
Steps where executed in root, so the target is a absolute file path.
=> repo symlink in /packages/

master-galera/master.cfg
The check now uses the os_i variable and not the os module
=> Fix check to identify Ubuntu 2004

docker-compose/.env, docker-compose/.env.dev, master-galera/master.cfg
Just a concept for making some stuff DEV only.
requires ENVIRON to be set in the master-private.cfg
=> env ENVIRON as DEV/PROD differenciator

docker-compose/generate-config.py
Ensure that the master-nonlatent and master-libvirt will be the first entries in the list, so that the port remains the same.
=> Re-organize docker-compose order

ci_build_images/debian.Dockerfile
This corrects ASAN failures on 10.4
Marko:
The reason is that the old PCRE (which was replaced in 10.5 by MDEV-14024) is really buggy. For ASAN, uninstrumented code is assumed to be good.
As only 10.4 needs this, and 10.5+ uses pcre2 and has mechisms to detect pcre2 over pcre(3) aka 8.x.
With this installed, the ASAN builder should autodetect WITH_PCRE=system. Currently without headers it fails to compile.
=> MDBF-620: Add libpcre3-dev to jammy for asan

ci_build_images/debian.Dockerfile
Should have been included in #221 change
They are in the artifacts buillt on galera.
=> Extend galera artifacts to lunar and mantic

common_factories.py, master-protected-branches/master.cfg
This is work-in-progress commit to have fast branch protection builders with a guarantee that a test, once failed, is fixed before further pushes are allowed. It works by running last N failed tests.
Note:
* it likely uses twisted incorrectly, needs to be fixed
* commit only provides a factory, it's not actually used for any builders, let's switch one builder over
After it is made to work and proves useful, needs to be extended as:
=> WIP: mtr run that runs last N failed tests

cross-reference/crossreference/cr/models.py
A limit of 5 doesn't show enough variety of errors to see if all branches are affected. A nieve usage could come to the conclusion that its not a common error.
The time of a 50 limit query isn't too much more,
so more is better.
=> cross-reference - default limit 50

utils.py
Since builders can run multiple MTR runs, the logs are organized in the form <mtr-run-name>/<log-files>. This means that having a direct link to var.tar.gz is no longer possible in the current form. This commit removes the broken link to var.tar.gz and updates the text of the current logs link to specify that the archive is found among the logs.
=> Change var.tar.gz link

docker-compose/docker-compose.yaml, docker-compose/generate-config.py
We should probably consider journald logging for buildbot containers too. But this seems like a big change and is not compatible with prod ATM.
=> Logging to journald for non builbot containers

master-docker-nonstandard/master.cfg
"/buildbot/installdb.sh " not found. We didn't download it with a space.
Can be run without a shell, easier to read quoting too.
+ blackify
=> eco: "/buildbot/installdb.sh " not found - space

.github/workflows/eco_containers.yml, eco_build_images/wordpress_phpunit_test_runner.Dockerfile
current test failures
```
license.txt's year needs to be updated to 2024.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'2024'
+'2023'
```
https://buildbot.mariadb.org/#/builders/505/builds/2721
so just bumping. Any bump pulls latest wordpress that has contraints https://github.com/WordPress/wordpress-develop/blob/trunk/package.json
=> wordpress bump

.github/workflows/bbw_build_container.yml, ci_build_images/README.md, constants.py
ref https://docs.fedoraproject.org/en-US/releases/eol/
We haven't announced a last release for FC37, which I assume we're doing this release. So merge after release.
=> Fedora 37 EOL

master-nonlatent/master.cfg
The extra testing on Windows packages is confusing so renaming it to "test extra" to better highlight that it's a testing step.
=> Rename Windows extra step

utils.py
The repository creation for Debian based OS needs to be reworked. This disables it and rollback to how we tested earlier. We might need to update the source list creation.
=> Disable repo creation

scripts/deb-install.sh
I am not entirely sure about this. My understanding is that the mirror setup (from deb.mariadb.org) should only be done for minor/major upgrades since the VM needs to install previous versions of MariaDB and then test the upgrade from artifacts. The test should be skipped if there is no previous version (minor/major) for the OS.
=> Comment mirror setup since install is done from BB artifacts

master-docker-nonstandard/master.cfg
Properly handle logs and create the var.tar.gz files for all MTR runs on the fulltest builder. After each MTR step, the mysqld* logs files are now stored in a separate directory. The behaviour is now consistent with other builders.
=> Create var and correctly handle logs for fulltest

scripts/bash_lib.sh, scripts/deb-install.sh
When doing installation test, we need to use the latest version of galera that was produced by BB.
=> Use galera from BB artifacts

scripts/bash_lib.sh, scripts/deb-install.sh, scripts/deb-upgrade.sh, scripts/rpm-upgrade.sh
follow-up on https://github.com/MariaDB/buildbot/pull/308
- Install previous major from archive if not available from rpm.mariadb.org;
- use socket for mariadb client;
- install only server/client packages for now (get back to a stable test/upgrade suite).
=> Improve rpm installation/upgrade scripts

scripts/bash_lib.sh
If not, on RHEL, it polutes output with:
"Not root, Subscription Management repositories not updated"
=> Repoquery needs to be run as root

scripts/bash_lib.sh
If not it may print not only packages but other informations (on RHEL for instance).
=> Repoquery needs to be run in quiet mode

scripts/rpm-upgrade.sh
It's necessary to remove old major version before upgrading packages. Not sure why, need to investigate if this is not something that we could fix to get closer from a "normal" upgrade scenario.
=> Rollback to previous major upgrade status

.github/workflows/bbw_build_container.yml, ci_build_images/README.md, ci_build_images/centos.Dockerfile
Build the images for the following builders:
* AlmaLinux 8,9
* Debian 12 386
* RockyLinux 8,9
=> Add missing builder images

docker-compose/docker-compose.yaml, docker-compose/generate-config.py, master-docker-nonstandard-2/buildbot.tac, master-docker-nonstandard-2/master.cfg, master-private.cfg-sample, validate_master_cfg.sh
The current master process already handles too many builds, so a new instance is needed. This new instance currently handles the following builders:
* amd64-debian-11-msan-clang-16
* x86-debian-12-fulltest
=> Add a new instance for master-docker-nonstandard

ci_build_images/README.md, ci_build_images/debian.Dockerfile
The new APT source list format is now default in Ubuntu 24.04 (was already in Debian Sid).
Make galera installation from BB CI more dynamic.
=> Deb sourcelist format change and galera deps installation

ci_build_images/fedora.Dockerfile
from [amd64-fedora-38-last-N-failed](https://buildbot.mariadb.org/#/builders/620)[2102](https://buildbot.mariadb.org/#/builders/620/builds/2102)debug-emb-ps test[stdio](https://buildbot.mariadb.org/#/builders/620/builds/2102/steps/20/logs/stdio):
```
select 2 is true = 3 AS `2 IS TRUE = 3`,2 is false = 3 AS `2 IS FALSE = 3`,/*always not null*/ 1 is null = 3 AS `2 IS UNKNOWN = 3`,/*always not null*/ 1 is null = 3 AS `2 IS NULL = 3`,/*always not null*/ 1 is null = 1 AS `ISNULL(2) = 1`
drop view v1;
- found 'core', moving it to '/home/buildbot/amd64-fedora-38-last-N-failed/build/mysql-test/var/11/log/main.precedence'
- found 'core' (1/1)
gdb not found, cannot get the stack trace
```
=> fedora - add gdb to build image

master-docker-nonstandard/master.cfg, utils.py
Disable the bg-bbw[4,5] builders since they have very high CPU IO wait time. Move the load to apexis-bbw3 for the builders using these machines including the ASAN builder mentioned in MDBF-660
=> MDBF-660 Move builders to other machines

constants.py, os_info.yaml
Also, remove the flag for operating systems that now should run upgrade tests
=> Rename has_install to has_upgrade

master-nonlatent/master.cfg
This is already covered by previous cleanup:
`name="cleanup", command="rm -r * .* 2> /dev/null || true", alwaysRun=True`
=> Un-necessary cleanup

ci_build_images/rhel.Dockerfile
As per #305, pmem needs to be remove from RHEL-8 and 9
=> Remove pmem from RHEL 8 and 9

constants.py, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg
This will replace amd64-debian-11-msan as a branch protection builder, so swapping the hardware used by one with the other.
=> Make amd64-debian-11-msan-clang-16 report to GitHub

master-nonlatent/master.cfg
The dockerlibrary builder is always triggered only if packages need to be saved, so set the save_packages property to False for the DEV builder.
=> Save images only on prod

.github/workflows/bbw_build_container.yml
- EOL end of June 2024;
- libpmem is only available on AMD64;
- libfmt is too old.
=> Disable buster build

scripts/bash_lib.sh
Error:
```console
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
```
From pgrep 4.0.2 (Debian 12)
=> Fix error on recent pgrep versions

master-web/master.cfg
We'll need to trigger on 11+ previews.
=> Get ready for 11+ previews

utils.py
Fedora case was always false (was only comparing one char), but given that we're only doing 38+ it doesn't matter any more.
Compact on rejections.
btw why is rocky compat being fetched on https://buildbot.mariadb.org/#/builders/654
=> hasCompat simplify

master-nonlatent/master.cfg
The tag must be added because the builder is used for branch protection
=> Add protected tag to aarch64-macos-compile-only

common_factories.py, scripts/bash_lib.sh
Error is:
```console
Last metadata expiration check: 0:00:02 ago on Thu 23 May 2024 11:16:33 AM UTC. |All matches were filtered out by modular filtering for argument: MariaDB-devel |  * Maybe you meant: mariadb-devel
All matches were filtered out by modular filtering for argument: MariaDB-server |  * Maybe you meant: mariadb-server
All matches were filtered out by modular filtering for argument: MariaDB-test |  * Maybe you meant: mariadb-test
```
See: https://buildbot.mariadb.org/#/builders/610/builds/1176
=> Repo needs to be adapted on all RHEL8 based distro

.github/workflows/bbw_build_container.yml, constants.py, master-config.yaml-sample, os_info.yaml
EOL according to https://mariadb.com/kb/en/mariadb-platform-deprecation-policy/.
@fauust VMs also need to be removed
=> EOL CentOS Stream 8

.github/workflows/bbw_build_container.yml, ci_build_images/mariadb_zypper_expect, ci_build_images/opensuse.Dockerfile
libfmt was added in 10.7 as a dependency. The autofetching mariadb-10.3 dependencies isn't enough. Also liburing was added as 10.6 improvement over libaio so include this.
=> opensuse15: add liburing2-devel and libfmt dependencies

ci_build_images/opensuse.Dockerfile
Not sure how it missed from being a mariadb build dependency.
=> opensuse: missing g++ from build

.github/workflows/bbw_build_container.yml
According to [MDBF-706] added aarch64 for almalinux 8 & 9.
=> build almalinux on aarch64

master-protected-branches/master.cfg
According to MDBF-715.
Based on: MDBF-654
This is a bug fix only manifesting itself in the Development environment because the changes did not reach Production yet.
=> Enable DEXTRA_DEBUG for amd64-ubuntu-2004-debug

master-docker-nonstandard/master.cfg
=> Add s390x-bbw workers for Ubuntu 20.04 debug builds

master-docker-nonstandard-2/master.cfg, script_templates/jepsen_mysql.sh
- download step
- add env vars
- solve bash issue that makes lein interpret "$LEIN_OPTIONS" as a single argument
=> Jepsen fixes

common_factories.py, constants.py, master-docker-nonstandard/master.cfg
As part of MDBF-653 we need to run Connect storage engine tests on a Builder.
Testing:
[amd64-ubuntu-2004-fulltest/18](https://buildbot.dev.mariadb.org/#/builders/183/builds/18)
- see [connect tests](https://buildbot.dev.mariadb.org/#/builders/183/builds/18/steps/27/logs/stdio)
- other tests were compared to a previous run [amd64-ubuntu-2004-fulltest/15 ](https://buildbot.dev.mariadb.org/#/builders/183/builds/15)
Selective regression testing:
- addTests function was modified to be general purpose so I've tested an autogen builder and compared it with a previous run to confirm that tests ran the same way as before.
- Test:  [aarch64-almalinux-8/16](https://buildbot.dev.mariadb.org/#/builders/124/builds/16)
=> MDBF 653 - Run Connect Tests as part of one builder in buildbot

common_factories.py
- added dependency for Galera test steps so they will not depend upon other test suites results but on Compile.
- previously the MTR step for galera was named "test" and was not obvious what we're testing.
=> MDBF-746 - Galera test suite always run

ci_build_images/fedora.Dockerfile
Was a cmake/rpm incompatibility that hit Fedora 39 (and 40 has a fixed version):
ref: MDEV-32741
ref: https://gitlab.kitware.com/cmake/cmake/-/issues/25421
Fedora isn't doing a version bump so we work around it: https://bugzilla.redhat.com/show_bug.cgi?id=2268060
```
CPackRPM:Debug:    - /buildtheveryveryveryveryveryveryveryverlongpathforrpmbuild/_CPack_Packages/Linux/RPM/rpmbuildMariaDB-backup.out
CPackRPM:Debug: *** Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1278201600
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.hrwwED
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.qIjJ8B
find-debuginfo: starting
Extracting debug info from 2 files
DWARF-compressing 2 files
sepdebugcrcfix: Updated 2 CRC32s, 0 CRC32s did match.
Creating .debug symlinks for …
```
=> fedora39: backport 3.28.5 CPackeRPM.cmake to build with rpm

constants.py, master-web/templates/grid_view/grid.jade, master-web/templates/home.jade
- added main to branches_main list so builders will be triggered on push
- if main will become 11.7, 11.8 and so on and every minor inherits builders from the previous minor version then main is a copy of supportedPlatform[latest]
=> MDBF-749 - support main branch

master-docker-nonstandard/master.cfg
- this change needs to be rollbacked until reported bugs on MDBF-741 are cleared up.
=> Rollback MDBF-740 clang usage on asan-ubsan

master-nonlatent/master.cfg
- ENVIRON environment variable is available for Development masters so the condition will evaluate to TRUE and set the correct path for the dev-worker on windows-bbw1 (currently the server hosting windows-packages builds)
=> MDBF-753 - Conditional paths for Development - windows_msi_env

common_factories.py
- by MDBF-736 a bug was introduced so the condition hasGalera and compile_step_completed was always evaluated to True because it will check that hasGalera it's a valid reference (TRUE) instead of calling it
- now doStepIf receives a lambda function that is evaluated at runtime so hasGalera can return True/False based on the builder name if it's in the builders_galera_mtr list
Previous broken runs (with old syntax):
[aarch64-almalinux-8/19 ](https://buildbot.dev.mariadb.org/#/builders/124/builds/19)
[amd64-debian-10/13 ](https://buildbot.dev.mariadb.org/#/builders/116/builds/13)
Here Galera tests are running even if the builders are missing from builders_galera_mtr list.
Fixed (new syntax):
[aarch64-almalinux-8/21 ](https://buildbot.dev.mariadb.org/#/builders/124/builds/21) …
=> Fix for MDBF-746 - quickBuild builders always ran Galera

ci_build_images/centos.Dockerfile, ci_build_images/fedora.Dockerfile, ci_build_images/opensuse.Dockerfile, ci_build_images/rhel.Dockerfile, ci_build_images/sles.Dockerfile
previously only Deb builds contained the latest galera package.
Include RPM based distros now.
=> Rpm galera

master-docker-nonstandard/master.cfg
As this isn't an out of tree build, the mtr must be run from the mysql-test directory otherwise:
sh -c 'MTR_FEEDBACK_PLUGIN=1 ASAN_OPTIONS="abort_on_error=1" LSAN_OPTIONS="print_suppressions=0,suppressions=$PWD/mysql-test/lsan.supp" mysql-test/mysql-test-run.pl --verbose-restart --force --retry=3 --max-save-core=2 --max-save-datadir=10 --max-test-fail=20 --mem --parallel=$(expr 20 \* 2)'
in dir /home/buildbot/amd64-debian-12-asan-ubsan/build (timeout 950 secs)
watching logfiles {'syslog': '/var/log/syslog'}
argv: [b'sh', b'-c', b'MTR_FEEDBACK_PLUGIN=1 ASAN_OPTIONS="abort_on_error=1" LSAN_OPTIONS="print_suppressions=0,suppressions=$PWD/mysql-test/lsan.supp" mysql-test/mysql-test-run.pl --verbose-restart --force --retry=3 --max-save-core=2 --max-save-datadir=10 --max-test-fail=20 --mem …
=> asan_ubsan: mtr path fix

common_factories.py, docker-compose/docker-compose.yaml, docker-compose/generate-config.py, master-nonlatent/master.cfg
- windows builders now support uploading mysql.err and var.tar.gz to CI for each MTR run.
- fixed URL's displayed in BB-UI for all File/Directory uploads
- refactored test code, introduced addWinTests function.
- for DEV,  master-nonlatent container has a volume mount on /srv/buildbot/packages (CI Uploads)
Tests:
- [amd64-windows](https://buildbot.dev.mariadb.org/#/builders/9/builds/4)
- [amd64-windows-packages](https://buildbot.dev.mariadb.org/#/builders/17/builds/58)
CI: 
- logs [windows](https://ci.dev.mariadb.org/13/logs/amd64-windows/) and[ windows-packages](https://ci.dev.mariadb.org/21/logs/amd64-windows-packages/)
=> MDBF - 645 - windows var.tar on CI

.github/workflows/bbm_deploy.yml
sometimes it's needed when Development environment it's in a bad state or multiple merges occurred and the workflow does not run in a FIFO manner
=> Manual workflow dispatch

ci_build_images/rhel.Dockerfile
lzo-devel needed for rhel 8 & 9
=> MDBF-763 - rhel8 and rhel9 builders don't have lzo

scripts/bash_lib.sh
11.0 is end of life so 11.1 has its previous release as 10.11.
because of maths rounding and imprecision 11.6.0 is being treated as 
https://buildbot.mariadb.org/#/builders/601/builds/455/steps/3/logs/stdio
```
+ [[ major == \m\a\j\o\r ]]
++ cut -d . -f1
+ old_branch_digit=10
++ cut -d . -f2
+ old_major_digit=11
++ cut -d . -f1
+ new_branch_digit=11
++ cut -d . -f2
+ new_major_digit=6
+ (( old_branch_digit == 10 ))
+ (( old_major_digit == 11 ))
+ (( new_branch_digit == 11 ))
+ (( new_major_digit != 0 ))
+ bb_log_err 'This does not look like a major upgrade from 10.11 to 11.0:'
+ set +x
ERROR: This does not look like a major upgrade from 10.11 to 11.0:
+ diff -u /tmp/version.old /tmp/version.new
--- /tmp/version.old	2024-07-26 21:15:59.316381612 +0000
+++ /tmp/version.new	2024-07-26 …
```
=> upgrade version - 11.6.0 the prev major_version wasnt 10.11

common_factories.py
To solve exception
https://buildbot.mariadb.org/#/builders/234/builds/31674
Scripts will run and do nothing if there is a compilation/packaging error.
=> Fix scripts generation - always run

dockerfiles/buildbot.tac
Failing builds, tac is missing
https://buildbot.mariadb.org/#/builders/237
=> Fix ECO images - rollback buildbot.tac

master-nonlatent/master.cfg
Use clang for the build because that's the FreeBSD default.
We use clang here to make it easy for FreeBSD ports maintainers.
=> MDBF-769: FreeBSD clang

.github/workflows/bbw_build_container_template.yml, .github/workflows/build-centos-based.yml, .github/workflows/build-centos.pip-based.yml, .github/workflows/build-centos7.pip-based.yml, .github/workflows/build-debian-based.yml, .github/workflows/build-debian.aocc-based.yml, .github/workflows/build-debian.jepsen-based.yml, .github/workflows/build-debian.msan-based.yml, .github/workflows/build-fedora-based.yml, .github/workflows/build-opensuse.pip-based.yml, .github/workflows/build-sles.pip-based.yml, .github/workflows/build-workflow-dispatcher.yml
@grooverdan  @fauust  @vladbogo . 
The core idea is to use GitHub reusable workflows to divide image builds into groups of parent workflows.
Based on the "matrix" in bbw_build_container.yml, parent workflows were created to reflect Dockerfile usage. Each workflow monitors changes in the corresponding Dockerfile, allowing for more granular control over which images are built. 
A master workflow, "build-workflow-dispatcher," is available to trigger all the child workflows manually or when the template is changed.
**Rollout Plan:**
- In bbw_build_container_template.yml, the PUSH to QUAY/GHCR is commented out so we can push this commit and perform regression tests against the current bbw_build_container workflow.
- All pending contributions to bbw_build_container should be rebased and adapted …
=> MDBF-770 - GitHub Reusable Workflows

os_info.yaml, schedulers_definition.py
Rocky to run install/upgrade tests with RHEL packages.
AlmaLinux back to install_only, as we just release RHEL packages.
=> MDBF-768 rhel to Rocky Linux install trigger

constants.py
Support for https://github.com/MariaDB/buildbot/pull/511 Master-NonLatent defines only one builder and one worker for dockerlibrary and wordpress. Rhel8 for Prod and Rhel9 for Dev.
So only one builder should be triggered.
=> BB - DEV  | DockerLibrary, Wordpress - builders

common_factories.py, master-nonlatent/master.cfg, scripts/docker-library-build.sh, scripts/docker-library-manifest.sh, scripts/docker-library-test.sh, utils.py
needs a build-arg support properly in the mariadb-docker repo for package names.
many other things to be tested properly in dev environment.
=> Docker Library to support UBI testing.

dockerfiles/eco-mysqljs-nodejs15-buster.dockerfile, dockerfiles/eco-php-ubuntu-2004.dockerfile, dockerfiles/eco-pymysql-python-3-9-slim-buster.dockerfile
- recent release (24.8.0) of automat package, installed from PIP, breaks twisted when starting buildbot-worker.
- 22.10 was tested locally that it solves the issue. Twisted is not enforcing an upper limit but requires automat >= 0.8.0
=> MDBF-776 - Automat 24.8.0 breaks with Twisted 23.8.0

common_factories.py, master-nonlatent/master.cfg
- rpm_autobake should provide UBI and GH_WORKFLOW properties. Default defined for Debian
- resulting wordpress image ends in ubi-wordpress
- extract last tag step should handle the file absence
- determine sha step should handle empty << tag >> array and should NOT run if lasttag file is not present
- gh credentials should not run if lastsha is empty or not defined
- test operator (GH workflow) should not run if lastsha is empty or not defined
The steps related to GH will be skipped when there is NO push to QUAY (last_tag file created == images were pushed to QUAY).
=> MDBF-777 - Fixes for UBI #511

scripts/docker-library-build.sh
master_branch is the main version, 11.5, however from 11.7 onwards is just "main".
This is what is in https://github.com/MariaDB/mariadb-docker.
As such, as a quick test, if the master_branch doesn't exist, use main on the assumption that its an 11.7+ branch.
example failure: https://buildbot.mariadb.org/#/builders/311/builds/24995
=> Docker Library - account for main branch

scripts/docker-library-build.sh
main_branch not used after this point.
branch needed the -ubi append.
=> Docker Library - account for main branch -ubi fix

.github/workflows/bbw_build_container_rhel.yml, .github/workflows/bbw_build_container_template.yml, .github/workflows/build-centos-based.yml, .github/workflows/build-centos.pip-based.yml, .github/workflows/build-debian-based.yml, .github/workflows/build-debian.msan-based.yml, .github/workflows/build-fedora-based.yml, .github/workflows/build-opensuse.pip-based.yml, .github/workflows/build-sles.pip-based.yml, ci_build_images/debian.Dockerfile
To solve chicken/egg problem of providing galera
workers to build the galera-4 package.
Once that happens, the nogalera can be removed form the attribute and the BB worker image will have the galera package needed to conduct galera tests.
=> MDBF-778 Add CI support for no-galera installation of workers

.github/workflows/build-centos.pip-based.yml, ci_build_images/centos.Dockerfile
As requested by @grooverdan at https://mariadb.zulipchat.com/#narrow/stream/451209-MariaDB-in-openEuler/topic/Buildbot.20CI.20image/near/463982676
To run: `buildah bud --build-arg BASE_IMAGE=docker.io/openeuler/openeuler:24.03-lts -f  centos.Dockerfile`
Note: openEuler does not have/need powertools/crb and yum-utils
=> Add support for openEuler OS (24.03 LTS)

ci_build_images/centos.Dockerfile
This is a temporary workaround to address the installation issue of the zope.interface package on the ppc64le architecture. I haven’t identified why the build succeeds on other architectures. Based on my observations, the installation fails with any version of setuptools greater than 70.*.
The latest release of setuptools in the 69.* series appears to work correctly, as most packages require a version greater than 61.*.
We need a more robust method for pinning package versions and managing updates in the future. Details of the failure can be found here: https://github.com/MariaDB/buildbot/actions/runs/10505629895/job/29103561343
@vladbogo  , @grooverdan  if you have better ideas how to handle this, please let me know.
=> MDBF-780 - CentOS Stream 9 - ppc - Image Build Failure

constants.py
Previously rocky/alma were switched to INSTALL_ONLY. Supported branches determines the triggering of these builders via the upstream scheduler.
fyi @grooverdan
=> Fix for MDBF-768 - rocky / alma are still triggered

.github/workflows/build-opensuse.pip-based.yml, .github/workflows/build-sles.pip-based.yml, ci_build_images/opensuse.Dockerfile, ci_build_images/sles.Dockerfile
Add 15.5 worker images.
Keep "15" as 15.6 for now for production compatibility.
Will do buildbot config in different PR due to build time on bbw.
=> MDBF-779 Sles/opensuse 15.5

.github/workflows/build-debian-based.yml, ci_build_images/debian.Dockerfile, constants.py, os_info.yaml
Set this for 11.4 branch on the hope that
the 11.4 from Debian sid can migrate to there
before release.
Like non-LTS Ubuntu distros only Aarch64/X86_64 architectures due to limited CI hardware.
- [?] Add builder configuration
=> MDBF-774 Add Ubuntu Oracular

.github/workflows/bbw_build_container_rhel.yml, ci_build_images/rhel.Dockerfile
@grooverdan  / @vladbogo 
Maybe it's time to switch to EPEL.
See:
```
docker run --rm -it -u root quay.io/mariadb-foundation/bb-worker:rhel9 bash
[@48969562dc17 buildbot]# uname -p
x86_64
[@48969562dc17 buildbot]# dnf list buildbot-worker
Available Packages
buildbot-worker.noarch  3.11.7el9 epel
docker run --rm --platform linux/ppc64le -it -u root quay.io/mariadb-foundation/bb-worker:rhel9 bash
[@331258cd83eb buildbot]# uname -p
ppc64le
[@331258cd83eb buildbot]# dnf list buildbot-worker
Available Packages
buildbot-worker.noarch  3.11.7-1.el9 epel
docker run --rm --platform linux/arm64 -it -u root quay.io/mariadb-foundation/bb-worker:rhel9 bash
[@022ae2241c2b buildbot]# uname -p
aarch64
[@022ae2241c2b buildbot]# dnf list buildbot-worker
Available Packages
buildbot-worker.noarch …
```
=> MDBF-783 - [GitHub] - Container image build failure for ubi9

ci_build_images/rhel.Dockerfile
Galera tests failing with WSREP_SST: [ERROR] 'rsync' not found in path (20240916 03:25:57.651)
See:
https://buildbot.mariadb.org/#/builders/728/builds/113/steps/8/logs/stdio
=> Add missing Galera dependencies - rhel - last-N-failed

scripts/docker-library-manifest.sh
jq --arg x v implies x is always a string. This
doesn't work when its compared to a number as as such all images are cleared.
Make removal around Dangling match the comment.
Ensure that buildah images removed have a mariadb name (otherwise it picks up ubuntu/mysql images in repo).
Simplify other select expressions to include more.
Yes, buildah and podman put different capitalization on .Id/.id files in json format
=> Docker Library - manifest cleanup

.github/workflows/build-centos7.pip-based.yml, ci_build_images/centos7.Dockerfile
This enables the EOL Centos7 with archived packages.
Then adds eigen3 to support MariaDB Vector.
=> MDBF-796 eigen centos7

utils.py
As per https://github.com/MariaDB/server/blob/8478a06cdbb7281e1cc2d507f18c985c736c2ffc/cmake/cpack_rpm.cmake#L374
MariaDB-compat won't be built for OpenEuler.
=> MDBF-796 - openeuler doesn't have compat rpm

master-docker-nonstandard/master.cfg
Clients in our binary taballs are linked dynamically with libncurses, which causes a trouble on systems where it is no longer available As per MDBF-794 only centos7 and debian 10 bintar builders need to link statically with libncurses.
- for debian 10: libncurses.a is already present in /scripts/local/lib/ and -DCURSES_NEED_NCURSES=1 flag is enough to link it statically.
- for centos7: I've rebuilt the image and pushed manually a dev_ tag. libncurses.a was present on the system but not in the library path: /scripts/local/lib/
Tests available at:
- debian10: https://buildbot.dev.mariadb.org/#/builders/187/builds/23
- centos7: https://buildbot.dev.mariadb.org/#/builders/172/builds/292
Reference CMAKE output line:
-- Found Curses: /scripts/local/lib/libncurses.a
=> MDBF-794 - Link bintar binaries statically with libncurses

.github/workflows/build-fedora-based.yml, constants.py, os_info.yaml
Closes https://github.com/MariaDB/buildbot/pull/563
Needed rebase + resolving conflicts.
=> MDBF-795: Add Fedora 41 (x86_64/Aarch64)

ci_build_images/centos.Dockerfile, ci_build_images/fedora.Dockerfile, ci_build_images/rhel.Dockerfile
Centos based have asio-devel in EPEL.
SLES is omitted as it requires a subpackage module repository to be enabled. Doing so would increase
the package dependencies when using the built packages. https://packagehub.suse.com/packages/asio/
(SLE-Module-PackageHub-Subpackages-Module )
On RHEL - asio-devel in ubi9 EPEL but not 8.
=> Add asio-devel to rpm based bb-worker images (galera build dependency, though bundled version exists)

utils.py
OpenSuse / Sles 15.x - do not need MariaDB-compat
=> [Post-fix][MDBF-779] OpenSuse / Sles 15.x - do not need MariaDB-compat

master-libvirt/master.cfg, scripts/bash_lib.sh, scripts/deb-upgrade.sh, scripts/rpm-upgrade.sh
… from old bb
Parts 1 and 2: Switching minor upgrade into "all" mode and extending it with additional checks (ldd, requirements, capabilities)
=> MDBF-800 Extend package minor upgrade tests to ensure transition

.github/workflows/build-debian-based.yml, constants.py, master.cfg, os_info.yaml
See: https://lists.debian.org/debian-announce/2024/msg00004.html
=> Support for PPC on Debian 11 is EOL

master-nonlatent/master.cfg
During the "Compile step" - create_initial_db.cmake runs a bootstrap as a sanity check to avoid spending time on test runs if the bootstrap fails.
It can happen that some changes on the server may cause a loop during the bootstrap process. Buildbot will terminate the parent process (dojob) when it reaches a timeout, but a MariaDB process will remain up causing new builds to fail. https://buildbot.mariadb.org/#/builders/234/builds/32911
Modified the stop_processes step to handle this.
=> Prevent MariaDB hanging process on Windows

scripts/bash_lib.sh
Improving build time by excluding the too many files of mariadb-test package from the ldd check when dependencies are collected.
[Disable previously enabled command logging in](https://github.com/MariaDB/buildbot/commit/0606a4e47ad843061895f90cfedab8833a772e57) https://github.com/MariaDB/buildbot/pull/582
=> MDBF-806 - Exclude LDD for mariadb-test packages

master-docker-nonstandard-2/master.cfg
The build runs --big-test which puts a lot of memory pressure on the machine, so adjusting the parallel to mitigate this.
=> Decrease parallel for x86-debian-12-fulltest

master-docker-nonstandard-2/master.cfg
Fixes https://github.com/MariaDB/buildbot/pull/585
=> [Mdev 31050][Post-Fix] - Enable cursor test on x86-debian-12-fulltest

master-galera/master.cfg
- easy to re-trigger all the builds.
- when new platforms are introduced one can trigger a build by re-building "trigger-galera-builds" for a particular revision . No need to wait for upstream changes to build on new platforms.
**Tests:**
https://buildbot.dev.mariadb.org/#/builders/435/builds/1
=> Dedicated builder for triggering Galera builds

ci_build_images/debian.Dockerfile, master-libvirt/master.cfg, os_info.yaml, scripts/bash_lib.sh, scripts/deb-upgrade.sh, scripts/rpm-upgrade.sh, utils.py
- [MDBF-803](https://jira.mariadb.org/browse/MDBF-803) - fixed finding mirror packages for previous OpenSuse 15.5/15.6 and CentosStream9
- add libmecab-dev to sort out LDD, REQ differences for `mariadb-plugin-mroonga`
- temporary adjustments for libaio/liburing and lsof to sort out the differences until Q4 release is done
- [Account for mariadb-plugin-mroonga diffs in Debian-11](https://github.com/MariaDB/buildbot/pull/596/commits/9db192c95fa30c9faf97ad560a0d0be92c354d66)
- fix upgrade script for OpenSuse - cache, install command, gpg key
- remove building compat for OpenSuse/SLES 15.x
=> [MDBF-800][Postfix] - fix minor upgrade all

ci_build_images/opensuse.Dockerfile, scripts/bash_lib.sh, scripts/rpm-upgrade.sh
- ID_LIKE may not exist
- upgrade command does not exist for zypper
- set delimiter for zypper packages -r output
- suppress libmecab diffs to account for old/new bb env diffs
- add krb5/judy/lzo to opensuse images to allow creating rpm packages for  lzo, oqgraph, and gssapi
=> mdbf-800 - SUSE fixes

ci_build_images/opensuse.Dockerfile
adding missing OpenSuse 15.x deps as per minor tests results in MDBF-813.
=> MDBF-813 - OpenSuse 15.x missing dependencies

ci_build_images/opensuse.Dockerfile
```
:~$ docker run --rm -it -u root quay.io/mariadb-foundation/bb-worker:dev_opensuse1505 bash  
0b0ed4c04573:/home/buildbot # rpm -qa | grep libedit 
libedit0-3.1.snap20150325-2.12.x86_64
libedit-devel-3.1.snap20150325-2.12.x86_64
:~$ docker run --rm -it -u root quay.io/mariadb-foundation/bb-worker:dev_opensuse1506 bash  
588c54d665b5:/home/buildbot # rpm -qa | grep libedit 
libedit0-3.1.snap20150325-2.12.x86_64
```
Build failure: https://buildbot.dev.mariadb.org/#/builders/418/builds/9
=> MDBF-813 - libedit-devel missing from OpenSuse 15.6

master-nonlatent/master.cfg
Without the MariaDB version specified, the operator was depending on a tag to identify the version. As we trigger by sha this needs to be specified.
Depends on https://github.com/mariadb-operator/mariadb-operator/pull/1048
=> docker library: trigger operator with mariadb_version

common_factories.py
We need to merge #585 to Production, which will enable the cursor tests on x86-debian-12-fulltest After the cursor tests are Stable we can enable them on the protected branches builder last-N-failed.
=> Revert part of #589 - cursor protocol tests on Last-N

common_factories.py
lots of failures across too many branches.
Some:
* crashes
* wrong result - needing 'select complicate_exp() as simplename`
* others general log requiring a view disable.
=> MDEV-35452 debug-view causing too many failures throughout spider

.github/workflows/eco_containers.yml
Trivial commit to get the build green again. Not harmful short term, but per MDBF-826  a different flow is needed.
Change to dev so the schedule (and merging this commit) will regenerate the wordpress container so its tests can pass.
A better long term strategy is in MDBF-826, because ultimately any change via schedule/commit in dev will go to prod.
=> MDBF-826 eco wordpress - retrigger build

utils.py
The UBI supported versions no are simplier - they just exclude 10.5.
With 11.1/11.2 releases done there the expression is simplier.
=> docker library: ubi now not-10.5/ 11.[12] last release

common_factories.py, constants.py, utils.py
- similar logic as in addGaleraTests
- the list is empty now (tests skipped), we should discuss what builders to run S3 tests.
- secrets provided by SecretInAFile provider. Secret file creation done manually on master host.
- mc client already installed on master containers, configured during master start-up (master-private). For PROD needs manual configuration.
=> MDBF-821 - Configure S3 tests

validate_master_cfg.sh
Simple fix, to allow running validate_master_cfg.sh multiple times locally.
=> validate_master_cfg.sh: do not fail if master-credential-provider exists

.github/workflows/bbm_build_container.yml, .github/workflows/bbm_deploy.yml, docker-compose/docker-compose.yaml, docker-compose/generate-config.py, validate_master_cfg.sh
**Main Feature:** [MDBF-791](https://jira.mariadb.org/browse/MDBF-791) - Run Production BuildBot services in docker containers
In this pull request:
- allow deployment of configuration files on new bbm PROD host
- only manually on workflow dispatch event and only for **Main** branch
- no service interaction. Only deploy configuration files, define Autogen/ masters and generate docker-compose file
- create DEV_tags for master containers.
- pushes to dev branch will create `dev_` tags
- **NO move tags for now.** We will update the Production tags **manually** until everything is stable enough.
- make docker-compose be aware of dev_ tags in Development environment.
- for bbm_deploy **check** step, validate both tags for each master to account for different BB versions (during upgrades for …
=> MDBF-832 & MDBF-828 - Prepare BBM deployment for Production

docker-compose/.env, docker-compose/.env.dev, docker-compose/docker-compose.yaml, docker-compose/generate-config.py, docker-compose/nginx/templates/bb.conf.template, docker-compose/nginx/templates/ci.conf.template
**Main feature**: [MDBF-791](https://jira.mariadb.org/browse/MDBF-791) - Run Production BuildBot services in docker containers
- **MQ_ROUTER_URL** for PROD will be the same as DEV, on 8080
- define **NGINX_CR_HOST_WG_ADDR** . For PROD is `hz-bbw5 on 8080`. For **DEV** we should deploy CR on `hz-dev-bbm` and choose another port (**8081**) because 8080 is already in use by CrossBar (MQ_ROUTER_URL)
- enable proxy pass to CrossReference in NGINX `bb.conf.template` and define ENV variable in docker-compose.
- by removing the logs mount, and custom logging in configs, NGINX container will now stream the default access / error logs to the standard out/err streams.
- having logging driver: `journald` will enable us to collect the logs via **journalctl** using the container tag **bb-nginx**.
=> MDBF-842 / MDBF-841 - Streaming NGINX logs to standard streams / evaluate .env files values

docker-compose/docker-compose.yaml, docker-compose/generate-config.py, docker-compose/mariadb-config/dev/mariadb.cnf, docker-compose/mariadb-config/prod/mariadb.cnf, docker-compose/mariadb.cnf, rsync.exclude
**Main feature**: [MDBF-791](https://jira.mariadb.org/browse/MDBF-791) - Run Production BuildBot services in docker containers
**In this Pull Request:**
- separate configs for PROD and DEV. 
- Updated docker-compose to choose the right one based on environment. 
- TODO: maybe a templating engine in the future to de-duplicate configuration settings.
**Q:**
->  @fauust how Restic backup will work for containers?
-> @grooverdan Couldn't find anything for slow query log in containers --> stdout (to be inspected with `docker logs `via `journald` driver). Anything like that possible? I've mounted a volume for these logs.
**Source of Truth:**
@fauust / @grooverdan For PROD configuration, well, my source of truth was hz-bbm1.
Here's the current prod layout, if you have any suggestions or I missed …
=> MDBF-829 - Update MariaDB Server cnf

common_factories.py, constants.py
S3 tests don't work for 10.5 (SSL No verify option is not present).
https://buildbot.mariadb.org/#/builders/369/builds/26765/steps/13/logs/stdio
Added `alwaysRun` option on `create bucket step` for the situation in which the previous test suite fails.
I've manually disabled these tests on PROD also until further notice.
I suggest we do the buildbot migration and then come back on this subject.
=> MDBF 135 - Don't run S3 for 10.5 / Use non-protected builders / Use SSL verification

utils.py
Otherwise aarch64-ubuntu-2004 will run S3 tests because the string is in aarch64-ubuntu-2004-debug
=> MDBF-135 Use exact match for builderName comparison in has S3

docker-compose/docker-compose.yaml, docker-compose/generate-config.py
Some factories are using the File/Directory upload steps to move files from the worker to CI. The data is transferred to the master which is then in charge of writing the files to destination on the host, meaning hz-bbm[1,2].
In order for this to work, the paths (from hz-bbm) should be mounted inside the container.
So far the following factories were identified:
-> f_asan_ubsan_build
-> f_big_test
-> f_asan_ubsan_build
-> f_valgrind_build
-> f_windows
-> f_windows_msi
Windows is defined by non-latent master which has already the path mounted. The rest of the factories are defined in master-docker-nonstandard 1 and 2.
For Linux builders is it possible to use a network file share but we will not cover this for the migration but taking a note for future refactoring.
=> MDBF-857 - Volume mounts for File/Upload steps

.github/workflows/bbm_build_container.yml
Main feature: [MDBF-791](https://jira.mariadb.org/browse/MDBF-791) - Run Production BuildBot services in docker containers
**Background:**
- when the branch is Main, create a copy of the Production tag {previous_master, previous_master-web}.
- in the future after the backup step, a "Move Tag" step will be added. For the moment we move dev_ tag to production manually.
**In this patch:**
- add MAIN_BRANCH environment variable. If branch is not main, no build, no backup creation.
@fauust @vladbogo let me know if that's a suitable approach.
Do you want backup on GHCR also?
Thanks.
=> MDBF-850 - Backup PROD master tag

docker-compose/docker-compose.yaml, docker-compose/generate-config.py, docker-compose/start-bbm-web.sh, docker-compose/start.sh
Need to replace the start.sh process with buildbot one when starting the master containers so docker-compose down SIGTERM will be handled by twisted for a graceful shutdown.
Also adding stop_grace_period to the master containers to allow for more than 10 seconds timeout before sending a SIGKILL.
=> MDBF-864 - Make master container handle SIGTERM

docker-compose/docker-compose.yaml, docker-compose/generate-config.py, docker-compose/nginx/templates/ci.conf.template
add /cloud-init location to expose required artifacts for libvirt cloud-init image deployment in Ansible
=> MDBF-865 - Nginx cloud-init location

.github/workflows/build-centos.pip-based.yml, .github/workflows/build-opensuse.pip-based.yml, ci_build_images/centos.Dockerfile, ci_build_images/opensuse.Dockerfile
With recently deployment and galera triggered the openeuler and opensuse images can now be build with a galera library for mtr testing.
Notably we couldn't enable a sles as there wasn't a sles1505 galera build.
=> MDBF-778 bbw: openeuler/opensuse galera ready

master-nonlatent/master.cfg
Otherwise it keeps whatever is on the local machine.
A pull always if it gets the same manifest will still use the local cached version.
=> wordpress: always pull latest image

.github/workflows/unittests.yml, Makefile, steps/cmake/compilers.py, steps/cmake/generator.py, steps/cmake/options.py, tests/test_cmake_generator.py
This commit introduces a utility class to allow for uniform construction of the MariaDB (& other projects) cmake step.
Usage is documented in the unit test.
* compilers.py -> Standard type-safe way of specifying the compiler command
* options.py -> Standard type-safe way of specifying CMAKE args. This file should be extended over time, as MariaDB's cmake flags change.
* generator.py -> Holds the CMake Generator class used to build the command argument.
This commit also introduces an additional workflow step, to make sure we run unit tests on the code.
=> Introduce a cmake generator class

common_factories.py
This is one PR out of a sequence to refactor code in BB to make it more maintainable.
This commit should not cause any practical functional changes (to check windows builder paths).
A list of refactoring changes covered in this PR:
1. Eliminate star imports. Import what you use.
2. Eliminate redundant f-strings without placeholders.
3. Fix wrong escape \ character in Windows-like paths.
4. Eliminate (some) long lines over 80 characters.
NOTE: I HAVE NOT TESTED THIS COMMIT. It should be run in dev to ensure it works.
=> Clean-up common_factories.py

.github/workflows/bbw_build_container_rhel.yml, .github/workflows/build-centos.pip-based.yml, .github/workflows/build-container-release.yml, .github/workflows/build-debian-based.yml, .github/workflows/build-debian.aocc-based.yml, .github/workflows/build-debian.jepsen-based.yml, .github/workflows/build-debian.msan-based.yml, .github/workflows/build-fedora-based.yml, .github/workflows/build-opensuse.pip-based.yml, .github/workflows/build-sles.pip-based.yml, .github/workflows/eco_containers.yml
Avoid building containers on BB repo push if branch is not DEV/MAIN
=> Avoid building containers on BB repo push if branch is not DEV/MAIN

common_factories.py, master-bintars/master.cfg, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg, master-galera/master.cfg, master-libvirt/master.cfg, master-nonlatent/master.cfg, master-protected-branches/master.cfg, master.cfg, utils.py
This PR introduces two changes:
1. Introduce type hints.
2. Clean up branch-prioritisation logic.
3. Removes unused code
The branch prioritisation logic should be double checked.
=> Refactor utils.py

master-bintars/master.cfg, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg, master-nonlatent/master.cfg, master-protected-branches/master.cfg, master.cfg, schedulers_definition.py
No need to reconstruct the same list over and over, just return a static variable.
NOTE: THIS PR WAS NOT TESTED
=> Refactor schedulers_definition.py

common_factories.py, constants.py, define_masters.py, locks.py, master-bintars/master.cfg, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg, master-galera/master.cfg, master-libvirt/get_ssh_cnx_num.py, master-libvirt/master.cfg, master-nonlatent/master.cfg, master-protected-branches/master.cfg, master-web/master.cfg, master.cfg, schedulers_definition.py, utils.py
This PR begins to refactor constants.py to declare constants as capital letters.
=> Rename constants to use capital letters consistently

common_factories.py, constants.py, define_masters.py, docker-compose/.env, docker-compose/.env.dev, master-bintars/master.cfg, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/master.cfg, master-galera/master.cfg, master-libvirt/master.cfg, master-nonlatent/master.cfg, master-private.cfg-sample, master-protected-branches/master.cfg, master-web/master.cfg, master.cfg, utils.py, validate_master_cfg.sh
Previously when the BuildBot **Production** environment was running on `systemd services`, we couldn't use the `.env `files defined in the project tree because they were specifically designed for usage in `docker-compose`. 
This led to hard coding variable defaults in the buildbot code, in the form of `os.getenv(#env_variable_for_containers#, default=#default_for_systemd#)`
**In this task:**
-> switch to a fail proof approach of loading variables using `os.environ` which will raise a `key not found exception` if the environment variable is not defined
-> adapt the GitHub CI script `validate_masters` to load the environment variables for each environment << dev , prod >>
-> remove "systemd" approach of loading PORTS for masters.
**This PR was tested using:**
`./validate_master_cfg.sh -e …
=> MDBF-876 - Remove BuildBot configuration code needed for systemd setup

utils.py
The line was lost during a rebase, making the function always return None
=> Fix rebase error: nextBuild should return which build to process

docker-compose/mariadb-config/prod/mariadb.cnf
We can increase replication storage on the BBM since storage is not limiting anymore. This will give us more time to fix replication problem if they occur in the future.
No impact on DEV, needs to be pushed on PROD but DB restart should probably be planned.
=> More storage on the new BBM (increase replication days)

common_factories.py, master.cfg, utils.py
This patch is mainly a fix for https://github.com/MariaDB/buildbot/pull/637 and a renaming suggestion for the `hasFiles` function to better highlight its purpose.
=> Fixes for #637 - ls2string does not append to the package list

scripts/bash_lib.sh
As investigated in https://jira.mariadb.org/browse/MDBF-887 by me and Elena, it seems that running LDD on
`ha_spider.so-10.6.20-1.el8.x86_64.debug` yields either return code 0 or 1 on different server versions with no really useful output for the comparison. Although the file is in ELF format and dynamically linked, LDD cannot provide any useful output.
```
ldd ha_spider.so-10.6.20-1.el8.x86_64.debug
ldd: warning: you do not have execution permission for `./ha_spider.so-10.6.20-1.el8.x86_64.debug'
$ echo $?
1
```
```
ldd ha_spider.so-10.6.21-1.el8.x86_64.debug
ldd: warning: you do not have execution permission for `./ha_spider.so-10.6.21-1.el8.x86_64.debug'
statically linked
$ echo $?
0
```
This underlying issue may be the subject to another task, for now in order to exclude the …
=> MDBF-887 - LDD Minor upgrade tests fail on RHEL ha_spider.so

ci_build_images/opensuse.Dockerfile, ci_build_images/sles.Dockerfile
This is 1/2 PR in the series for solving **MDBF-882**. It will align `buildbot.mariadb.{NET,ORG}` in terms of produced packages by fixing ColumnStore package creation for MariaDB Server versions 10.5, 10.6, 10.11
ColumnStore package creation for 11.4 onward will be solved in a separate PR as it needs more attention.
**How to test this PR:**
-> pull an opensuse/sles container image from quay -> install the missing libraries added in this PR
-> follow build instructions on any opensuse / sles autobake builder -> check that the CS package was produced.
**How to deploy to Production:**
-> after the OpenSuse/Sles images are re-generated in DEV, sync with Main branch and the GitHub workflow
will automatically promote it to Production.
=> MDBF-882 - ColumnStore packages not created for OpenSuse/Sles

ci_build_images/sles.Dockerfile
This is a fix for https://github.com/MariaDB/buildbot/pull/681
While boost components were installed on SLES, the CS package was still missing. After doing a `CMAKE --trace` I've found out that `limbxml2` is missing.
```
MESSAGE_ONCE(CS_NO_LIBXML Could not find a usable libxml2 development environment! )
```
Tested locally with the current **sles1506** container image and after installing `libxml2-devel`, the CS packages are generated for mariadb server 10.11.
=> MDBF-882 - ColumnStore Package not created on SLES

os_info.yaml
Fix the repository path to /sles15-amd64/rpms/ for upgrade tests.
buildbot.mariadb.net has only one builder (sles 15 sp3) which is providing packages on the mirror and all paths on the repository are just symlinks.
To be decided how these paths will be adjusted when SLES 15 SP7 will be released, and we will have both SP6 and SP7 creating packages.
=> MDBF-899 - SLES version_name RPM

docker-compose/docker-compose.yaml, docker-compose/generate-config.py
Buildbot calculate the container name on a worker host based on the sha of the master name.
If the master name is the same between dev / prod, which is true at this moment (both environments running in containers), then when the same builder runs on the same host on both environments a conflict will occur causing one of the builds to fail and retry.
`Error: The container name "/buildbot-hz-bbw1-docker-tarball-debian-12-15cc21" is already in use by container `
This is an error on the development environment when a build << tarball-docker >> was already running in production on hz-bbw1.
Sometimes builds get stuck in "Preparing worker" state and Production is affected. This is why this patch is important, because we can impact Production during our tests in buildbot.dev.mariadb.org
=> MDBF-933 - DockerLatentWorker containers name not unique

ci_build_images/bintar.Dockerfile, ci_build_images/scripts/ncurses.sh, master-docker-nonstandard/master.cfg
We have lbtinfo.so.6 as an extra dependency for mariadb client. This is because not all functions are found in libncurses.a during configure and CMAKE will fallback to using the ones found in libtinfo shared library.
In this task ncurses.sh was modified to recompile the library, statically, with embedded libtinfo. Details on the approach is documented in the script itself.
The second issue this patch solves is removing the duplicate libgalera_smm.so that is packaged by CPACK, previously configured by CMAKE with -DEXTRA_FILES
The galera library is the latest found in ci.mariadb.org, but we should further discuss the process of including galera into binary tarballs. So far, in old-bb, the binary tarball's were re-packaged and galera was included during every release.
=> MDBF-935 - recompile libncurses.a, rm duplicate galera

scripts/docker-library-build.sh, scripts/docker-library-manifest.sh, scripts/docker-library-test.sh
debug info containers disabled for now. Scripts test locally ok when passed same BB arguments.
1. Save space
Rather than building parts of the manifest on the assumption that all architectures will catch up, wait for all of them.
When the are all there, build them all in one go, and clean them all up at the end.
The *-reference.txt file contains the name of the builders that are ready. Its used as a counter so the only thing that matters is the number of unique lines.
Removed use of podman. There where probably some incompatible things here.
2. be retriggerable
If any part of the build fails, clean the images up. Any manual retrigger on the tarbuildnum for a ubi/non-ubi will retrigger the building of the manifest, and test. This saves us rebuilding the packages.
So this includes …
=> docker library: build when all base packages are ready

common_factories.py
As requested by @mmontes.
same interface: https://github.com/mariadb-operator/mariadb-operator/blob/main/.github/workflows/test-image-ubi.yml
=> MDBF-939: MariaDB Operator to use ubi workflow rather than ent

master-nonlatent/master.cfg, scripts/docker-library-build.sh, scripts/docker-library-manifest.sh
showed in last step of build
https://buildbot.dev.mariadb.org/#/builders/4/builds/72
```
+ '[' linux/amd64 = amd64 ']'
program finished with exit code 0
elapsedTime=84.804340
```
The trigging of wordpress also is after the manifest is built.
=> docker library: arch match against amd64 incorrect for tagging wordpress

master-nonlatent/master.cfg, scripts/docker-library-build.sh, scripts/docker-library-manifest.sh, scripts/docker-library-test.sh
non-fatal things are listed as warnings so its easy to look at bb interface to see which docker library job actually did the work rather than just skipping.
concept from https://github.com/MariaDB/buildbot/pull/697#issuecomment-2633503606
=> docker library: use DecodeRC for warnings

master-nonlatent/master.cfg
If any of the three docker-library scripts return a status of 2 and are marked with warnings, the entire build instance should be marked as completed with warnings. This way, we can easily inspect which builds are in this state
=> MDBF-940: Steps with warnings should flag the entire build

constants.py
Now that `s3.mysqldump` was resolved for the Main branch we can finally add S3 tests to branch protection.
See MDEV-35921:  https://github.com/MariaDB/server/commit/b8fa8b9b3d108002ada5715e12e935219490270c
and buildbot S3 run: https://buildbot.mariadb.org/#/builders/538/builds/23207/steps/13/logs/stdio
```
s3.amazon                                w15 [ skipped ]  Not connected to AWS
s3.unsupported                           w18 [ pass ]    192
s3.backup                                w19 [ pass ]    209
s3.select                                w14 [ pass ]    394
s3.debug                                 w10 [ pass ]    487
s3.encryption                            w3 [ pass ]    563
s3.partition_create_fail                 w13 [ pass ]    402
s3.arguments                             w7 [ …
```
=> MDBF-135 - Add MTR S3 on protected builder amd64-ubuntu-2004-debug

.github/workflows/bbm_deploy.yml, buildbot.tac, common_factories.py, constants.py, define_masters.py, docker-compose/start-bbm-web.sh, docker-compose/start.sh, master-docker-nonstandard-2/buildbot.tac, master-docker-nonstandard-2/master.cfg, master-docker-nonstandard/buildbot.tac, master-docker-nonstandard/master.cfg, master-galera/buildbot.tac, master-galera/master.cfg, master-libvirt/buildbot.tac, master-libvirt/master.cfg, master-nonlatent/buildbot.tac, master-nonlatent/master.cfg, master-protected-branches/buildbot.tac, master-protected-branches/master.cfg, master-web/buildbot.tac, master-web/master.cfg, master.cfg, master_common.py, os_info.yaml, utils.py, validate_master_cfg.sh
This is a cleanup PR that should not impact the builders / workers actually running tests.
=> Refactor master cfg

ci_build_images/scripts/gnutls.sh
In almalinux bintar we bundle all symbols into gnutls.a (the server
expects it like that). However for parsec plugin, cmake looks for
libhogweed and libnettle. These should be bundled as static libraries
separately as well. Including the header files.
=> MDEV-35844: Parsec plugins missing from generic binary tarball

ci_build_images/scripts/ncurses.sh
NCURSES rely on terminfo database to find out what are the terminal capabilities so that keypresses are interpreted as intended.
In our case, backspace was interpreted as a simple space " ". terminfo database is available on most linux distributions by default so we just need to set the paths when compiling ncurses statically.
Example strace output of mariadb client after testing with this patch applied to ncurses:
```
stat("/home/razvan/.terminfo", 0x64c0fac3e450) = -1 ENOENT (No such file or directory)
stat("/etc/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/lib/terminfo", 0x64c0fac3e4e0)   = -1 ENOENT (No such file or directory)
stat("/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/scripts/local//share/terminfo", 0x64c0fac3e570) = -1 …
```
=> MDEV-35844 - ncurses wrong terminfo database path

docker-compose/start.sh
Libvirt authenticates with qemu+ssh to hosts that provide VM workers. It requires the private key for the session user and the list of known hosts.
Since the script was adapted to the new buildbot.tac paths, we need to ensure that we locate the two files mentioned above and copy them into the .ssh directory of the master container's user.
=> MDBF-712 Fix Libvirt startup script

.github/workflows/bbm_deploy.yml, worker_locks.yaml
Given that we have 5 s390x VM instances, each configured with 8vCPU's, we need to consider lowering the number of parallel builds on each VM from 3 to 1.
The builds are running Make with a parallel of 7 thus the 1 build per VM.
=> MDBF-967 - Lower the number of parallel builds on s390x

locks.py
Currently `locks.py` doesn't work in BuildBot because the script is checking if the **runtime worker_name** is in LOCKS dictionary by the full name of the worker which is composed by a `worker_base + OS`
Examples:
- runtime worker_name: s390x-bbw4-docker-ubuntu-2204
- worker_name (base) in worker_locks.yaml: s390x-bbw4-docker
Implemented a for loop to check if the base name is in the runtime worker_name string instead.
=> MDBF-972 - Fix Master Global Locks

master-web/master.cfg
We write the http master-web log file in the wrong path.
Previously relative to the master directory and currently,
in the root path of the buildbot deployment after the .tac update
```
$ find . -type f -name "http.log*" -exec realpath {} \;
/srv/dev/master-web/http.log
/srv/dev/http.log.2
/srv/dev/http.log.14
/srv/dev/http.log.16
...
```
This patch will change the http log dir to the common Logs folder for all masters.
Expected location after this patch
```
$ find . -type f -name "master-web-www.log*" -exec realpath {} \;
/srv/dev/docker-compose/logs/master-web-www.log
```
=> MDBF-973 Fix master-web http log location

master-docker-nonstandard/master.cfg
**hz-bbw5**
- RAM: 128 GB
- CPU's : 32, 1 socket, 64 threads
Current docker workload:
```
amd64-debian-12-asan-ubsan
- > Jobs = 20
amd64-debian-12-rocksdb
- > Jobs = 20
amd64-debian-11-msan-clang-16
-> Jobs = 30
```
In the worst case scenario, all three builders requesting a build on `hz-bbw5` would result in **70/64** CPU parity which is not acceptable given that:
- we run libvirt workers for amd64 on this machine
- we run mariadb replica (crossreference) on this machine
=> MDBF-981 hz-bbw5 - OOM due to docker workload requestion too much resources

scripts/bash_lib.sh
The upgrade from 11.8.1 to 12.0.0 is legit but `check_upgraded_versions()` was not patched to handle it.
```
+ check_upgraded_versions
+ for file in /tmp/version.old /tmp/version.new
+ [[ -f /tmp/version.old ]]
+ for file in /tmp/version.old /tmp/version.new
+ [[ -f /tmp/version.new ]]
+ [[ major == \m\a\j\o\r ]]
++ cut -d . -f1
+ old_branch_digit=11
++ cut -d . -f2
+ old_major_digit=8
++ cut -d . -f1
+ new_branch_digit=12
++ cut -d . -f2
+ new_major_digit=0
+ (( old_branch_digit == 10 ))
+ old_major_digit_incr=9
+ (( old_major_digit_incr == new_major_digit ))
+ bb_log_err 'This does not look like a major upgrade:'
+ set +x
ERROR: This does not look like a major upgrade:
+ diff -u /tmp/version.old /tmp/version.new
--- /tmp/version.old	2025-02-20 03:19:38.015106234 -0500
+++ …
```
=> MDBF-980 - libvirt: Handle Major update from 11.8 to 12.0

master-docker-nonstandard-2/master.cfg
Fix for: https://github.com/MariaDB/buildbot/pull/670
Although the debian-12-i386 container image is build with the 32-bit toolchain, from compiler to mariadb build time dependencies,
CMAKE will detect the host system (docker host) arch, it will think it's x86_x64 and will attempt to build rocksdb see: https://github.com/MariaDB/server/commit/3eb8bc740817aa7010a070be0699bff6266f829c
This will cause the builds on the debug builder to fail, as warnings are treated as termination errors. https://buildbot.dev.mariadb.org/#/builders/533/builds/4
```
/home/buildbot/x86-debian-12-fulltest-debug/build/storage/rocksdb/ha_rocksdb.cc: In function ‘int myrocks::rocksdb_init_func(void*)’:
/home/buildbot/x86-debian-12-fulltest-debug/build/storage/rocksdb/ha_rocksdb.cc:5492:39: error: format ‘%ld’ …
```
=> Disable plugin rocksdb for i386, cmake doesn't know the intended target

.codespellrc, .pylintrc, steps/base/exceptions.py, steps/base/generator.py, steps/base/options.py, steps/cmake/generator.py, steps/cmake/options.py, steps/mtr/generator.py, steps/mtr/options.py, tests/test_cmake_generator.py, tests/test_mtr_generator.py
This PR introduces an MTR Generator so we can standardise MTR invocation. It's likely not in its final form, we will likely have to add ENVIRONMENT variables support, for MTR_FEEDBACK_PLUGIN=1 for instance, but this will happen when we have specific builders use this class. For now the code is not used in any buildbot config, although it does have unit tests.
Refactoring:
Extract the base common logic from CMakeGenerator and put it into the "base" folder instead.
=> MDBF-994: MTR Generator to unify mtr invocation in Buildbot

constants.py
Part of MDBF-993.
As per @cvicentiu  request,
**last-N-failed** is only reporting its status (not in branch protection) and @cvicentiu reported often sporadic failures for it.
**debian-11-msan** It will be replaced by a clang-20 builder in https://github.com/MariaDB/buildbot/pull/562 so no need to update GITHUB_STATUS_BUILDERS for it in this Pull Request.
=> MDBF-993 Remove amd64-debian-11-msan and last-N-failed from status reporting

constants.py
Rectifing Debug build failures has stalled on some review and further test failures are known. As such disable this for now.
Move the non-debug to 10.6 branch where tests are being fixed. Remain C/C update approved, and one archive-big test mask waiting to be fixed in server branches.
=> MDBF-793: clang 20 msan builder

constants.py
For the mtr tests around unix socket that depend on this env variable.
Given the presence of the tests and the long availablility of unix socket I'm not expecting the mtr tests to fail because of this change.
=> MDBF-1020 buildbot workers needs env USER=buildbot

.github/workflows/bbw_build_container_rhel.yml, ci_build_images/rhel7.Dockerfile, constants.py, os_info.yaml
This is a revert of https://github.com/MariaDB/buildbot/commit/c5ff095750aee990e2190d90e2cb2b4ded41dd21
Additional changes:
- build RH7 only for server versions <= 10.11
- use archived EPEL repository
- use galera from ci.mariadb.org. #TODO: update it to latest version
- install missing dependencies to build all already released packages on mirror
- use multi-stage build in base dockerfile for clarity
VM (install / upgrade):
- VM already deployed on APEXIS by Faustin. Will sync for PROD after DEV testing
=> MDBF-978 Reinstate RHEL 7 Builder

.github/workflows/bbw_build_container_rhel.yml, ci_build_images/rhel7.Dockerfile
- upgrade pip
- latest buildbot worker 4.2.x does not work on python 3.6
- don't use pip.Dockerfile
- rhel9 ppc64le needs a newer qemu-user-static to build (e.g. newer github runner) https://gitlab.com/qemu-project/qemu/-/issues/1471
Tests:
https://github.com/MariaDB/buildbot/actions/runs/14260753047/job/39971625922
=> MDBF-978 - fix pip buildbot-worker

ci_build_images/rhel7.Dockerfile
MTR fails at invocation if the path is not set to a valid lib even if the test suite is not galera
```
mysql-test-run: *** ERROR: WSREP_PROVIDER env set to an invalid path
```
=> MDBF-978 - fix wsrep path to galera-4

master-web/master.cfg
Rationale:
- refs/pull/#id#/merge is not always updated right after someone pushes a commit on the source PR branch, causing buildbot to test on older versions of the branch
- /head ref is always showing the developer intention testing on his/her version of the codebase
- integration testing will still happen because, right before merging the PR, branch policies will enforce a rebase
=> MDBF-1014 - use refs/pull/#id#/head for Pull-Request changes

master-nonlatent/master.cfg
macos aws instances run the buildbot-worker under a different user. the user is already exposed in the environment and the unix socket tests are running
This is a quick fix to preserve user:buildbot in MTR_ENV.
=> MDBF-1020 - macos user != buildbot

scripts/bash_lib.sh
$ID_LIKE is undefined in OpenEuler.
=> MDBF-1043 - ID_LIKE undefined on OpenEuler

ci_build_images/msan.fragment.Dockerfile
This is adding a few extension needed for ASAN/UBSAN so its ready. Added to msan so we don't need to maintain two similar containers.
Reusing MSAN container as latest clang also
provides up to date ASAN/UBSAN. The MSAN work
is isolation to the side.
Also with rr in this container it provides a
single portablility of recordings which is
dependent on rr versoin.
ASAN/UBSAN_OPTIONS to facilitate base debugging
from Roel.
Take suppression files and put these in the
image as a reference, but also for CI to
be able to pull the latest an update is needed.
=> MDBF-740/741 ASAN/UBSAN to MSAN container

scripts/rpm-install.sh
Workaround for
```
ERROR 2026 (HY000) at line 1: TLS/SSL error: unexpected eof while reading
```
during
```
+ sudo mariadb --verbose -e 'create database cs;     use cs;     create table cs.t_columnstore (a int, b char(8)) engine=Columnstore;     insert into cs.t_columnstore select seq, concat('\''val'\'',seq) from seq_1_to_10;     select * from cs.t_columnstore'
```
until https://jira.mariadb.org/browse/MCOL-5825 is sorted out.
=> MDBF-1046 - stream 10 disable CS tests during Install

constants.py
As such the 11.4 sid install tests fail and there's no point doing them any more.
=> Debian sid now on 11.8

master-web/master.cfg
There are enabled by default[1], however interfere without our protected branch status of buildbot.
[1] https://docs.buildbot.net/current/manual/configuration/wwwhooks.html#github-hook
=> MDBF-1058: ignore github skip ci directives

master-nonlatent/master.cfg
If the connection is lost in a non-clean fashion then:
- current run:  the build dir won't be cleaned
- next run:  will fail and perform the cleanup as a last step.
- third run:  will run as expected (starting with an empty build dir)
=> MDBF-1062 - macos cleanup previous build artifacts

utils.py
RPM compat files aren't needed
anywhere anymore.
This will wait until https://github.com/MariaDB/server/pull/3666 is merged up to the last main branch before merging into production.
The only that was using it, RHEL8 (not s390x),
was incorrect.
=> MDEV-35512 remove RPM compat for 11.4+

scripts/bash_lib.sh
See:
```console
❯ wget --version
GNU Wget 1.25.0 built on linux-musl.
❯ wget --spider --server-response https://rpm.mariadb.org/10.10/fedora40-aarch64; echo $?
[..]
8
❯ wget --version
GNU Wget2 2.2.0 - multithreaded metalink/file/website downloader
❯ wget --spider --server-response https://rpm.mariadb.org/10.10/fedora40-aarch64; echo $?
[..]
0
```
This change makes behavior the same for both versions.
=> MDBF-1040: wget and wget 2 behaves differently

common_factories.py, constants.py, master-docker-nonstandard-2/master.cfg, master-web/templates/grid_view/grid.jade, master-web/templates/home.jade, scripts/aix-build-and-test.sh, utils.py
This patch is targeted for buildbot release v1.0.7 I know I had an attempt to cover it in
https://github.com/MariaDB/buildbot/pull/756
but I don't like getting merge conflicts on constants.py. so it's better to separate the concerns a bit,
remove 10.5 and then handle any platform deprecation / addition.
=> MDBF-1074 - EOL 10.5

ci_build_images/rhel.Dockerfile
no point linking to userspace if the kernel didn't support it.
MariaDB containers are RHEL9 based.
=> MDBF-1042: RHEL8 has no kernel uring - aio only

configuration/builders/sequences/release.py, configuration/steps/base.py
- fix make order, `package_source` should be first to avoid packing build artifacts in the `.src.rpm`
- improved the steps summary by adding `descriptionDone` . This will avoid showing the entire `docker run` command
=> MDBF-809 - fix make order in master migration RPM autobake

.github/workflows/build-fedora-based.yml, constants.py, os_info.yaml
[2/4] patch in the series.
Merge after https://github.com/MariaDB/buildbot/pull/774
=> MDBF-1060 - Fedora 40 is EOL - remove release builders

ci_build_images/rhel7.Dockerfile
Create cpack -> cpack3 symlink
```
[root@5f79c6a59763 buildbot]# source /etc/os-release
[root@5f79c6a59763 buildbot]# echo $VERSION
7.9 (Maipo)
[root@5f79c6a59763 buildbot]# cpack
bash: cpack: command not found
[root@5f79c6a59763 buildbot]# cpack3 --version
cpack3 version 3.17.5
CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@5f79c6a59763 buildbot]# ln -sf /usr/bin/cpack3 /usr/bin/cpack
[root@5f79c6a59763 buildbot]# cpack --version
cpack3 version 3.17.5
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
=> MDBF-1086 - gal-amd64-rhel-7 missing cpack -> cpack3 symlink

master-private.cfg-sample
Will handle file changes manually on both environments. 
Builds are scheduled based on host load and the data is retrieved from Zabbix based on the following mapping `private_config["private"]["worker_name_mapping"][worker_prefix]` 
s390x master restart is required.
=> s390x-bbw1 host was upgraded from EOL 2004 to 2404

ci_build_images/rhel7.Dockerfile
sorry - should have seen this at the same time.
Create ctest -> ctest3 symlink
```
[buildbot@6f5dbfde1c6a ~]$ source /etc/os-release
[buildbot@6f5dbfde1c6a ~]$ echo $VERSION
7.9 (Maipo)
[buildbot@6f5dbfde1c6a ~]$ ctest
bash: ctest: command not found
[buildbot@6f5dbfde1c6a ~]$ ctest3 --version
ctest3 version 3.17.5
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
=> MDBF-1086 - gal-amd64-rhel-7 missing ctest -> ctest3 symlink

docker-compose/docker-compose.yaml
Sporadicaly, the master-web process disconnect from crossbar and brings buildbot web interface down. In order to investigate this problem, we need more logs. We are not sure that it's related to crossbar but that's an option.
Error is on master-web:
| Guru meditation! We have been disconnected from wamp server
=> MDBF-188: we need more crossbar logs

master-galera/master.cfg
The debian builds in scripts/build.sh already use JOBS
```
DEB_BUILD_OPTIONS="version=$GALERA_VER revno=$GALERA_REV parallel=$JOBS ...
```
This add it to RPMs also in anticipation being used there too.
https://github.com/MariaDB/galera/pull/37#discussion_r2181146501
=> Galera (revert old) + JOBS env variable for RPM and Deb build

master-nonlatent/master.cfg
Failing MTR tests can result in stuck processes, which may cause the cleanup step to fail. 
Subsequent builds may also fail if they run in a non-empty build directory. 
Add mysqld to the `stop_processes` step.
=> Windows - PermissionDenied: (mysqld.exe:FileInfo)

scripts/bash_lib.sh
libaio1 added as a dependency legitimately in MDEV-36234. It's normal to see differences during ldd tests between the packages on mirror and what is currently build.
To avoid false-positives better ignore the differences generated by the extra dependency, until Q3 2025 release. After the community server release, we can remove the workaround.
=> MDBF-1091 ignore libaio1 on ldd minor upgrade tests

master-galera/master.cfg
https://buildbot.dev.mariadb.org/#/builders/675/builds/3
```
buildbot.process.remotecommand.RemoteException: b'builtins.RuntimeError': 'env' values must be strings or lists; key 'JOBS' is incorrect Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 216, in maybeDeferred result = f(*args, **kwargs) File "/usr/local/lib/python3.11/site-packages/buildbot_worker/commands/shell.py", line 27, in start c = runprocess.RunProcess( File "/usr/local/lib/python3.11/site-packages/buildbot_worker/runprocess.py", line 394, in __init__ raise RuntimeError( builtins.RuntimeError: 'env' values must be strings or lists; key 'JOBS' is incorrect
```
Fix: https://buildbot.dev.mariadb.org/#/builders/675/builds/4
```
environment: …
```
=> Fix galera jobs

scripts/docker-library-build.sh
To get past:
error: Your local changes to the following files would be overwritten by checkout:
11.6-ubi/MariaDB.repo
11.7-ubi/MariaDB.repo
e.g.
https://buildbot.mariadb.org/#/builders/311/builds/30522
=> docker library: git checkout -f

ci_build_images/fedora.Dockerfile, ci_build_images/opensuse.Dockerfile, ci_build_images/pip.Dockerfile, ci_build_images/sles.Dockerfile
found in  #3301, assuming its a new hadolint version.
ci_build_images/fedora.Dockerfile:12 SC3046 warning: In POSIX sh, 'source' in place of '.' is undefined.
So used a . instead.
=> hadolint dislikes source

scripts/docker-library-build.sh, scripts/docker-library-manifest.sh, utils.py
Adjust the triggers for Docker Library:
* 10.11 /10.6 are being triggered incorrectly.
* Add RHEL10 as base for MariaDB-12+
Supported by https://github.com/MariaDB/mariadb-docker/pull/653
=> Docker library (fix 20.04 EOL) + RHEL10 base

.github/workflows/bbw_build_container_rhel.yml, .github/workflows/build-centos.pip-based.yml, .github/workflows/build-debian-based.yml, .github/workflows/build-fedora-based.yml, .github/workflows/build-sles.pip-based.yml, ci_build_images/fedora.Dockerfile
From https://buildbot.mariadb.org/#/grid?branch=mariadb-4.x
Fedora:
- arm fedora 41: https://buildbot.mariadb.org/#/builders/855/builds/41
- amd fedora 41: https://buildbot.mariadb.org/#/builders/851/builds/41
- arm fedora 42: https://buildbot.mariadb.org/#/builders/934/builds/7
- amd fedora 42: https://buildbot.mariadb.org/#/builders/935/builds/7
RHEL:
- amd rhel 10: https://buildbot.mariadb.org/#/builders/930/builds/7
- arm rhe 10: https://buildbot.mariadb.org/#/builders/936/builds/7
- ppc rhel 10: https://buildbot.mariadb.org/#/builders/927/builds/9
- s390x rhel 10: https://buildbot.mariadb.org/#/builders/938/builds/8
CENTOS:
- amd stream 10: https://buildbot.mariadb.org/#/builders/865/builds/32
- arm stream 10: https://buildbot.mariadb.org/#/builders/863/builds/33
- ppc stream 10: …
=> MDBF-811 - galera-4 CI build package is available  on all supported distros

scripts/bash_lib.sh
Avoids current error:
INFO: storing Columnstore logs in columnstore_logs
cat: /tmp/columnstore_tmp_files/rdwrscratch: Is a directory
e.g.: https://buildbot.mariadb.org/#/builders/823/builds/415
=> get_columnstore_logs: save if file only

scripts/bash_lib.sh
Ubuntu-2204-deb-autobake-minor-upgrade-all (and 2404)
-----------------
mariadb-test-data:
-  Depends: libc6
-  Depends: libpam0g
=> MDBF-1099 Temporarly Ignore mariadb-test-data dropping deps

common_factories.py
1200 seconds timeout seems to be too low, building an rpm MariaDB-test package often is killed because of this timeout. rpmbuild apparently goes over all files in the package, and mysql-test has a lot of files.
=> MDBF-1101 - RPM build package 1200s timeout is too low

scripts/rpm-upgrade.sh
As per MDEV-33459, major upgrades within the same family (>10) and vendor (!=distro) should work without removing old packages first.
=> MDBF-1121 - libvirt - RPM automatic upgrades

.github/workflows/build-debian-based.yml, constants.py, os_info.yaml
11.8 is being packaged in distro
https://packages.ubuntu.com/questing/mariadb-server
=> MDBF-1116: Add Ubuntu 25.10 Questing

.github/workflows/build-fedora-based.yml, .github/workflows/build-opensuse.pip-based.yml, .github/workflows/build-srpm.yml, ci_build_images/fedora.Dockerfile, ci_build_images/opensuse.Dockerfile, ci_build_images/srpm.Dockerfile, constants.py, os_info.yaml
=> MDBF-1117: Add Fedora 43 and MDBF-1118 and OpenSUSE 16.0
